In [1]:
import pandas as pd
import numpy as np

In [2]:
user_df = pd.read_csv("/content/user.csv")
tourism_df = pd.read_csv("/content/tourism_with_id.csv")
rating_df = pd.read_csv("/content/tourism_rating.csv")
package_df = pd.read_csv("/content/package_tourism.csv")
wisata_df = pd.read_csv("/content/data_wisata_indonesia1.csv")

print("\n--- User Data (user_df) ---")
user_df.info()
print(user_df.head())
print("\n--- Tourism Data with ID (tourism_df) ---")
tourism_df.info()
print(tourism_df.head())
print("\n--- Tourism Rating Data (rating_df) ---")
rating_df.info()
print(rating_df.head())
print("\n--- Package Tourism Data (package_df) ---")
package_df.info()
print(package_df.head())
print("\n--- Wisata JSON Data (wisata_json_df) ---")
wisata_df.info()
print(wisata_df.head())

--- User Data (user_df) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   User_Id   300 non-null    int64
 1   Location  300 non-null    object
 2   Age       300 non-null    int64
dtypes: int64(2), object(1)
memory usage: 7.2+ KB
   User_Id                   Location  Age
0        1      Semarang, Jawa Tengah   20
1        2         Bekasi, Jawa Barat   21
2        3        Cirebon, Jawa Barat   23
3        4         Bekasi, Jawa Barat   21
4        5  Lampung, Sumatera Selatan   20

--- Tourism Data with ID (tourism_df) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 437 entries, 0 to 436
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Place_Id      437 non-null    int64
 1   Place_Name    437 non-null    object
 2   Description   437 non-null    object
 3   Category      437 non-null    object
 4   City          437 non-null    object
 5   Price         437 non-null    int64
 6   Rating        437 non-null    float64
 7   Time_Minutes  205 non-null    float64
 8   Coordinate    437 non-null    object
 9   Lat           437 non-null    float64
 10  Long          437 non-null    float64
 11  Unnamed: 11   0 non-null      float64
 12  Unnamed: 12   437 non-null    int64
dtypes: float64(5), int64(3), object(5)
memory usage: 44.5+ KB
   Place_Id                         Place_Name  \
0         1                   Monumen Nasional
1         2                           Kota Tua
2         3                      Dunia Fantasi
3         4  Taman Mini Indonesia Indah (TMII)
4         5           Atlantis Water Adventure

                                         Description       Category     City  \
0  Monumen Nasional atau yang populer disingkat d...         Budaya  Jakarta
1  Kota tua di Jakarta, yang juga bernama Kota Tu...         Budaya  Jakarta
2  Dunia Fantasi atau disebut juga Dufan adalah t...  Taman Hiburan  Jakarta
3  Taman Mini Indonesia Indah merupakan suatu kaw...  Taman Hiburan  Jakarta
4  Atlantis Water Adventure atau dikenal dengan A...  Taman Hiburan  Jakarta

    Price  Rating  Time_Minutes  \
0   20000     4.6          15.0
1       0     4.6          90.0
2  270000     4.6         360.0
3   10000     4.5           NaN
4   94000     4.5          60.0

                                        Coordinate       Lat        Long  \
0          {'lat': -6.1753924, 'lng': 106.8271528} -6.175392  106.827153
1  {'lat': -6.137644799999999, 'lng': 106.8171245} -6.137645  106.817125
2  {'lat': -6.125312399999999, 'lng': 106.8335377} -6.125312  106.833538
3  {'lat': -6.302445899999999, 'lng': 106.8951559} -6.302446  106.895156
4             {'lat': -6.12419, 'lng': 106.839134} -6.124190  106.839134

   Unnamed: 11  Unnamed: 12
0          NaN            1
1          NaN            2
2          NaN            3
3          NaN            4
4          NaN            5

--- Tourism Rating Data (rating_df) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   User_Id        10000 non-null  int64
 1   Place_Id       10000 non-null  int64
 2   Place_Ratings  10000 non-null  int64
dtypes: int64(3)
memory usage: 234.5 KB
   User_Id  Place_Id  Place_Ratings
0        1       179              3
1        1       344              2
2        1         5              5
3        1       373              3
4        1       101              4

--- Package Tourism Data (package_df) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Package         100 non-null    int64
 1   City            100 non-null    object
 2   Place_Tourism1  100 non-null    object
 3   Place_Tourism2  100 non-null    object
 4   Place_Tourism3  100 non-null    object
 5   Place_Tourism4  66 non-null     object
 6   Place_Tourism5  39 non-null     object
dtypes: int64(1), object(6)
memory usage: 5.6+ KB
   Package     City         Place_Tourism1      Place_Tourism2  \
0        1  Jakarta      Pasar Tanah Abang        Taman Ayodya
1        2  Jakarta      Pasar Tanah Abang  Pasar Taman Puring
2        3  Jakarta  Perpustakaan Nasional               Monas
3        4  Jakarta           Pulau Tidung      Pulau Bidadari
4        5  Jakarta  Museum Satria Mandala       Museum Wayang

          Place_Tourism3                                     Place_Tourism4  \
0         Museum Tekstil                                                NaN
1   Pasar Petak Sembilan                                                NaN
2        Masjid Istiqlal                                                NaN
3             Pulau Pari                                      Pulau Pramuka
4  Museum Bahari Jakarta  Museum Macan (Modern and Contemporary Art in N...

  Place_Tourism5
0            NaN
1            NaN
2            NaN
3  Pulau Pelangi
4            NaN

--- Wisata JSON Data (wisata_json_df) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nama          190 non-null    object
 1   jenis wisata  179 non-null    object
 2   deskripsi     179 non-null    object
 3   provinsi      190 non-null    object
 4   lokasi        190 non-null    object
 5   long          190 non-null    float64
 6   lang          190 non-null    float64
dtypes: float64(2), object(5)
memory usage: 10.5+ KB
                                 nama jenis wisata  \
0                         Kuala Pasai  Wisata Alam
1  gaya highland sign hollywood style  Wisata Alam
2                   Eko Wisata Payani  Wisata Alam
3                         Simpang Air  Wisata Alam
4                    Bivak 1 Panorama  Wisata Alam

                       deskripsi provinsi   lokasi       long      lang
0  Tempat wisata menarik di Aceh     Aceh     Aceh  97.226341  5.152063
1  Tempat wisata menarik di Aceh     Aceh     Aceh  96.853408  4.612208
2  Tempat wisata menarik di Aceh     Aceh  BIreuen  96.832108  5.193299
3  Tempat wisata menarik di Aceh     Aceh     Aceh  97.227552  3.968151
4  Tempat wisata menarik di Aceh     Aceh     Aceh  97.219310  3.961753

# gabungkan data tourism_with_id dengan data_wisata_indonesia1

In [3]:
import pandas as pd

# Load Data
tourism_df = pd.read_csv("/content/tourism_with_id.csv")
wisata_df = pd.read_csv("/content/data_wisata_indonesia1.csv")

# Perbaiki nama kolom 'lang' jadi 'lat'
wisata_df = wisata_df.rename(columns={'lang': 'lat'})

# Ambil list nama tempat wisata dari tourism_df
existing_places = tourism_df['Place_Name'].tolist()

# Filter data wisata_df yang nama wisatanya belum ada di tourism_df
new_wisata_df = wisata_df[~wisata_df['nama'].isin(existing_places)].copy()

# Buat Place_Id baru mulai dari max(Place_Id)+1
max_place_id = tourism_df['Place_Id'].max()
new_wisata_df['Place_Id'] = range(max_place_id + 1, max_place_id + 1 + len(new_wisata_df))

# Susun dataframe hasil merge dari new_wisata_df
new_wisata_df_clean = new_wisata_df[['Place_Id', 'nama', 'deskripsi', 'jenis wisata', 'lokasi', 'lat', 'long']].copy()
new_wisata_df_clean = new_wisata_df_clean.rename(columns={
    'nama': 'Place_Name',
    'deskripsi': 'Description',
    'jenis wisata': 'Category',
    'lokasi': 'City',
    'lat': 'Lat',
    'long': 'Long'
})

# Tambahkan kolom Price dan Rating default 0
new_wisata_df_clean['Price'] = 0
new_wisata_df_clean['Rating'] = 0

# Kolom Time_Minutes, Coordinate, Unnamed: 11, Unnamed: 12 dibuat default None/NaN
new_wisata_df_clean['Time_Minutes'] = None
new_wisata_df_clean['Coordinate'] = None
new_wisata_df_clean['Unnamed: 11'] = None
new_wisata_df_clean['Unnamed: 12'] = None

# Susun urutan kolom biar sama kayak tourism_df
new_wisata_df_clean = new_wisata_df_clean[tourism_df.columns]

# Gabungkan dengan tourism_df
combined_tourism_df = pd.concat([tourism_df, new_wisata_df_clean], ignore_index=True)

# Cek hasil
print("\n--- Combined Tourism Data ---")
combined_tourism_df.info()
print(combined_tourism_df.head())
print(f"\nTotal data setelah digabung: {combined_tourism_df.shape[0]} baris")

--- Combined Tourism Data ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 626 entries, 0 to 625
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Place_Id      626 non-null    int64
 1   Place_Name    626 non-null    object
 2   Description   615 non-null    object
 3   Category      615 non-null    object
 4   City          626 non-null    object
 5   Price         626 non-null    int64
 6   Rating        626 non-null    float64
 7   Time_Minutes  205 non-null    float64
 8   Coordinate    437 non-null    object
 9   Lat           626 non-null    float64
 10  Long          626 non-null    float64
 11  Unnamed: 11   0 non-null      object
 12  Unnamed: 12   437 non-null    object
dtypes: float64(4), int64(2), object(7)
memory usage: 63.7+ KB
   Place_Id                         Place_Name  \
0         1                   Monumen Nasional
1         2                           Kota Tua
2         3                      Dunia Fantasi
3         4  Taman Mini Indonesia Indah (TMII)
4         5           Atlantis Water Adventure

                                         Description       Category     City  \
0  Monumen Nasional atau yang populer disingkat d...         Budaya  Jakarta
1  Kota tua di Jakarta, yang juga bernama Kota Tu...         Budaya  Jakarta
2  Dunia Fantasi atau disebut juga Dufan adalah t...  Taman Hiburan  Jakarta
3  Taman Mini Indonesia Indah merupakan suatu kaw...  Taman Hiburan  Jakarta
4  Atlantis Water Adventure atau dikenal dengan A...  Taman Hiburan  Jakarta

    Price  Rating  Time_Minutes  \
0   20000     4.6          15.0
1       0     4.6          90.0
2  270000     4.6         360.0
3   10000     4.5           NaN
4   94000     4.5          60.0

                                        Coordinate       Lat        Long  \
0          {'lat': -6.1753924, 'lng': 106.8271528} -6.175392  106.827153
1  {'lat': -6.137644799999999, 'lng': 106.8171245} -6.137645  106.817125
2  {'lat': -6.125312399999999, 'lng': 106.8335377} -6.125312  106.833538
3  {'lat': -6.302445899999999, 'lng': 106.8951559} -6.302446  106.895156
4             {'lat': -6.12419, 'lng': 106.839134} -6.124190  106.839134

  Unnamed: 11 Unnamed: 12
0         NaN           1
1         NaN           2
2         NaN           3
3         NaN           4
4         NaN           5

Total data setelah digabung: 626 baris

<ipython-input-3-73a3280255eb>:45: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_tourism_df = pd.concat([tourism_df, new_wisata_df_clean], ignore_index=True)

In [4]:
# Hapus kolom yang tidak diperlukan
combined_tourism_df.drop(columns=['Coordinate', 'Unnamed: 11', 'Unnamed: 12'], inplace=True)

# Cek hasil setelah penghapusan kolom
print("\n--- Data setelah kolom tak penting dihapus ---")
print(combined_tourism_df.info())
print(combined_tourism_df.head())

--- Data setelah kolom tak penting dihapus ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 626 entries, 0 to 625
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Place_Id      626 non-null    int64
 1   Place_Name    626 non-null    object
 2   Description   615 non-null    object
 3   Category      615 non-null    object
 4   City          626 non-null    object
 5   Price         626 non-null    int64
 6   Rating        626 non-null    float64
 7   Time_Minutes  205 non-null    float64
 8   Lat           626 non-null    float64
 9   Long          626 non-null    float64
dtypes: float64(4), int64(2), object(4)
memory usage: 49.0+ KB
None
   Place_Id                         Place_Name  \
0         1                   Monumen Nasional
1         2                           Kota Tua
2         3                      Dunia Fantasi
3         4  Taman Mini Indonesia Indah (TMII)
4         5           Atlantis Water Adventure

                                         Description       Category     City  \
0  Monumen Nasional atau yang populer disingkat d...         Budaya  Jakarta
1  Kota tua di Jakarta, yang juga bernama Kota Tu...         Budaya  Jakarta
2  Dunia Fantasi atau disebut juga Dufan adalah t...  Taman Hiburan  Jakarta
3  Taman Mini Indonesia Indah merupakan suatu kaw...  Taman Hiburan  Jakarta
4  Atlantis Water Adventure atau dikenal dengan A...  Taman Hiburan  Jakarta

    Price  Rating  Time_Minutes       Lat        Long
0   20000     4.6          15.0 -6.175392  106.827153
1       0     4.6          90.0 -6.137645  106.817125
2  270000     4.6         360.0 -6.125312  106.833538
3   10000     4.5           NaN -6.302446  106.895156
4   94000     4.5          60.0 -6.124190  106.839134

In [5]:
# prompt: cek duplikasi Place_Name dan nilai unik dari City dan categori

# Cek duplikasi pada kolom 'Place_Name'
print("\n--- Cek Duplikasi 'Place_Name' ---")
duplicated_place_names = combined_tourism_df[combined_tourism_df.duplicated(subset=['Place_Name'], keep=False)]
if not duplicated_place_names.empty:
  print("Terdapat duplikasi pada 'Place_Name':")
  print(duplicated_place_names.sort_values(by='Place_Name'))
else:
  print("Tidak ada duplikasi pada kolom 'Place_Name'.")

# Cek nilai unik pada kolom 'City'
print("\n--- Nilai Unik 'City' ---")
unique_cities = combined_tourism_df['City'].unique()
print(f"Jumlah nilai unik pada kolom 'City': {len(unique_cities)}")
print("Nilai unik 'City':")
print(unique_cities)

# Cek nilai unik pada kolom 'Category'
print("\n--- Nilai Unik 'Category' ---")
unique_categories = combined_tourism_df['Category'].unique()
print(f"Jumlah nilai unik pada kolom 'Category': {len(unique_categories)}")
print("Nilai unik 'Category':")
unique_categories

--- Cek Duplikasi 'Place_Name' ---
Terdapat duplikasi pada 'Place_Name':
     Place_Id                      Place_Name  \
487       488                           Ancol
497       498                           Ancol
509       510                      Batu Tulis
504       505                      Batu Tulis
490       491                    Eka Lokasari
500       501                    Eka Lokasari
563       564        For going to LOVE ISLAND
562       563        For going to LOVE ISLAND
502       503                           Ketep
507       508                           Ketep
588       589                     Lava stones
589       590                     Lava stones
492       493  Mekarsari Amazing Tourism Park
488       489  Mekarsari Amazing Tourism Park
503       504    Museum Perjuangan Yogyakarta
508       509    Museum Perjuangan Yogyakarta
501       502                     Stasiun Tas
491       492                     Stasiun Tas
595       596          Tempat tidak ditemukan
603       604          Tempat tidak ditemukan
612       613          Tempat tidak ditemukan
605       606          Tempat tidak ditemukan
613       614          Tempat tidak ditemukan
604       605          Tempat tidak ditemukan
594       595          Tempat tidak ditemukan
615       616          Tempat tidak ditemukan
570       571          Tempat tidak ditemukan
614       615          Tempat tidak ditemukan
593       594          Tempat tidak ditemukan
498       499                   Wayang Museum
489       490                   Wayang Museum
580       581            Wisata Kebun Stoberi
578       579            Wisata Kebun Stoberi
579       580            Wisata Kebun Stoberi

                                   Description       Category  \
487       Tempat wisata menarik di DKI Jakarta    Wisata Alam
497            Tempat wisata menarik di Banten    Wisata Alam
509     Tempat wisata menarik di DI Yogyakarta    Wisata Alam
504       Tempat wisata menarik di Jawa Tengah    Wisata Alam
490       Tempat wisata menarik di DKI Jakarta    Wisata Alam
500            Tempat wisata menarik di Banten    Wisata Alam
563         Tempat wisata menarik di Gorontalo    Wisata Alam
562         Tempat wisata menarik di Gorontalo    Wisata Alam
502       Tempat wisata menarik di Jawa Tengah    Wisata Alam
507     Tempat wisata menarik di DI Yogyakarta    Wisata Alam
588      Tempat wisata menarik di Maluku Utara    Wisata Alam
589      Tempat wisata menarik di Maluku Utara    Wisata Alam
492        Tempat wisata menarik di Jawa Barat    Wisata Alam
488       Tempat wisata menarik di DKI Jakarta    Wisata Alam
503       Tempat wisata menarik di Jawa Tengah  Wisata Budaya
508     Tempat wisata menarik di DI Yogyakarta  Wisata Budaya
501            Tempat wisata menarik di Banten    Wisata Alam
491       Tempat wisata menarik di DKI Jakarta    Wisata Alam
595                                        NaN            NaN
603                                        NaN            NaN
612                                        NaN            NaN
605                                        NaN            NaN
613                                        NaN            NaN
604                                        NaN            NaN
594                                        NaN            NaN
615                                        NaN            NaN
570                                        NaN            NaN
614                                        NaN            NaN
593                                        NaN            NaN
498            Tempat wisata menarik di Banten  Wisata Budaya
489       Tempat wisata menarik di DKI Jakarta  Wisata Budaya
580  Tempat wisata menarik di Sulawesi Selatan    Wisata Alam
578  Tempat wisata menarik di Sulawesi Selatan    Wisata Alam
579  Tempat wisata menarik di Sulawesi Selatan    Wisata Alam

                 City  Price  Rating  Time_Minutes       Lat        Long
487       DKI Jakarta      0     0.0           NaN -6.125028  106.841379
497            Banten      0     0.0           NaN -6.125028  106.841379
509     DI Yogyakarta      0     0.0           NaN -7.446099  110.437726
504       Jawa Tengah      0     0.0           NaN -7.446099  110.437726
490       DKI Jakarta      0     0.0           NaN -6.621889  106.817470
500            Banten      0     0.0           NaN -6.621889  106.817470
563         Gorontalo      0     0.0           NaN  0.490463  122.304566
562         Gorontalo      0     0.0           NaN  0.490464  122.304553
502       Jawa Tengah      0     0.0           NaN -7.582006  110.447696
507     DI Yogyakarta      0     0.0           NaN -7.582006  110.447696
588      Maluku Utara      0     0.0           NaN  0.846299  127.366803
589      Maluku Utara      0     0.0           NaN  0.848422  127.362625
492        Jawa Barat      0     0.0           NaN -6.411604  106.987995
488       DKI Jakarta      0     0.0           NaN -6.411604  106.987995
503        Yogyakarta      0     0.0           NaN -7.816471  110.371832
508        Yogyakarta      0     0.0           NaN -7.816471  110.371832
501            Banten      0     0.0           NaN -6.618648  106.821353
491       DKI Jakarta      0     0.0           NaN -6.618648  106.821353
595             Ambon      0     0.0           NaN -3.695400  128.190000
603            Nabire      0     0.0           NaN -3.366700  135.497000
612           Merauke      0     0.0           NaN -8.466700  140.403800
605            Nabire      0     0.0           NaN -3.366700  135.497000
613           Merauke      0     0.0           NaN -8.466700  140.403800
604            Nabire      0     0.0           NaN -3.366700  135.497000
594             Ambon      0     0.0           NaN -3.695400  128.190000
615           Merauke      0     0.0           NaN -8.466700  140.403800
570              Palu      0     0.0           NaN -0.891700  119.870700
614           Merauke      0     0.0           NaN -8.466700  140.403800
593             Ambon      0     0.0           NaN -3.695400  128.190000
498      West Jakarta      0     0.0           NaN -6.134815  106.812509
489      West Jakarta      0     0.0           NaN -6.134815  106.812509
580  Sulawesi Selatan      0     0.0           NaN -5.244504  119.896098
578  Sulawesi Selatan      0     0.0           NaN -5.240274  119.889285
579  Sulawesi Selatan      0     0.0           NaN -5.241238  119.891087

--- Nilai Unik 'City' ---
Jumlah nilai unik pada kolom 'City': 53
Nilai unik 'City':
['Jakarta' 'Yogyakarta' 'Bandung' 'Semarang' 'Surabaya' 'Aceh' 'BIreuen'
 'Medan' 'Sumatera Utara' 'Sumatera Barat' 'Riau' 'Kepulauan Riau'
 'Singapore' 'Jambi' 'Sumatera Selatan' 'Bangka Belitung' 'Bengkulu'
 'Lampung' 'DKI Jakarta' 'West Jakarta' 'Jawa Barat' 'Banten'
 'Jawa Tengah' 'Surakarta' 'DI Yogyakarta' 'Jawa Timur' 'Peterongan'
 'Bali' 'Nusa Tenggara Barat' 'Nusa Tenggara Timur' 'Kalimantan Barat'
 'Kalimantan Tengah' 'Kalimantan Selatan' 'Kalimantan Timur'
 'Kalimantan Utara' 'Sulawesi Utara' 'Gorontalo' 'Sulawesi Tengah' 'Palu'
 'Sulawesi Barat' 'Sulawesi Selatan' 'Sulawesi Tenggara' 'Maluku Utara'
 'Maluku' 'Ambon' 'Papua Barat' 'Papua Tengah' 'Nabire' 'Papua'
 'Papua Selatan' 'Merauke' 'Papua Barat Daya' 'Papua Pegunungan']

--- Nilai Unik 'Category' ---
Jumlah nilai unik pada kolom 'Category': 12
Nilai unik 'Category':

array(['Budaya', 'Taman Hiburan', 'Cagar Alam', 'Bahari',
       'Pusat Perbelanjaan', 'Tempat Ibadah', 'Wisata Alam',
       'Wisata Budaya', 'Wisata Petualangan', 'Wisata Hiburan',
       'Wisata Kuliner', nan], dtype=object)

In [6]:
import pandas as pd
import numpy as np

# --- 1. Hapus duplikasi Place_Name, simpan yang paling lengkap ---
# Hitung jumlah NaN per baris
combined_tourism_df['missing_count'] = combined_tourism_df.isnull().sum(axis=1)

# Urutkan dataframe berdasarkan Place_Name dan jumlah missing_value (yang paling sedikit ke atas)
combined_tourism_df = combined_tourism_df.sort_values(by=['Place_Name', 'missing_count'])

# Drop duplikat Place_Name, simpan yang pertama (yang paling lengkap)
combined_tourism_df_cleaned = combined_tourism_df.drop_duplicates(subset='Place_Name', keep='first')

# Hapus kolom bantu missing_count
combined_tourism_df_cleaned = combined_tourism_df_cleaned.drop(columns='missing_count')

# --- 2. Mapping City jadi seragam ---
city_mapping = {
    'DKI Jakarta': 'Jakarta',
    'West Jakarta': 'Jakarta',
    'Yogyakarta': 'Yogyakarta',
    'DI Yogyakarta': 'Yogyakarta',
    'Jawa Tengah': 'Jawa Tengah',
    'Jawa Timur': 'Jawa Timur',
    'Jawa Barat': 'Jawa Barat',
    'Sulawesi Selatan': 'Sulawesi Selatan',
    'Palu': 'Sulawesi Tengah',
    'Ambon': 'Maluku',
    'Nabire': 'Papua',
    'Merauke': 'Papua',
}

# Terapkan mapping
combined_tourism_df_cleaned['City'] = combined_tourism_df_cleaned['City'].replace(city_mapping)

# --- (Opsional) Cek hasilnya ---
print("\n--- Nilai Unik 'City' Setelah Mapping ---")
print(combined_tourism_df_cleaned['City'].unique())

# Cek apakah masih ada duplikasi Place_Name
print("\n--- Cek Duplikasi 'Place_Name' Setelah Dibersihkan ---")
print(combined_tourism_df_cleaned.duplicated(subset='Place_Name').sum())

--- Nilai Unik 'City' Setelah Mapping ---
['Papua' 'Papua Tengah' 'Riau' 'Surabaya' 'Jambi' 'Semarang' 'Yogyakarta'
 'Jakarta' 'Bandung' 'Bali' 'Sulawesi Utara' 'Papua Barat Daya'
 'Kalimantan Tengah' 'Sulawesi Tengah' 'Kalimantan Barat' 'Jawa Tengah'
 'Aceh' 'Kepulauan Riau' 'Singapore' 'Sulawesi Barat' 'Papua Pegunungan'
 'Bengkulu' 'Nusa Tenggara Timur' 'Sumatera Selatan' 'Kalimantan Selatan'
 'Banten' 'BIreuen' 'Maluku Utara' 'Gorontalo' 'Sumatera Barat'
 'Sulawesi Selatan' 'Jawa Timur' 'Kalimantan Utara' 'Bangka Belitung'
 'Sumatera Utara' 'Sulawesi Tenggara' 'Kalimantan Timur' 'Jawa Barat'
 'Medan' 'Nusa Tenggara Barat' 'Maluku' 'Lampung' 'Peterongan'
 'Papua Selatan' 'Surakarta' 'Papua Barat']

--- Cek Duplikasi 'Place_Name' Setelah Dibersihkan ---
0

In [7]:

print("\n--- Cek Nilai Null pada Lat dan Long ---")
print("Nilai null pada kolom 'Lat':", combined_tourism_df_cleaned['Lat'].isnull().sum())
print("Nilai null pada kolom 'Long':", combined_tourism_df_cleaned['Long'].isnull().sum())

--- Cek Nilai Null pada Lat dan Long ---
Nilai null pada kolom 'Lat': 0
Nilai null pada kolom 'Long': 0

In [8]:
# Membandingkan jumlah Place_Id unik dengan jumlah baris
num_unique_place_ids = combined_tourism_df_cleaned['Place_Id'].nunique()
num_rows = combined_tourism_df_cleaned.shape[0]

print(f"\nJumlah Place_Id unik: {num_unique_place_ids}")
print(f"Jumlah baris dataframe: {num_rows}")

if num_unique_place_ids == num_rows:
  print("Jumlah Place_Id unik sama dengan jumlah baris.")
else:
  print("Jumlah Place_Id unik TIDAK sama dengan jumlah baris.")

Jumlah Place_Id unik: 604
Jumlah baris dataframe: 604
Jumlah Place_Id unik sama dengan jumlah baris.

In [9]:

# Cek apakah ada nilai 0 atau null pada kolom 'Rating' di combined_tourism_df_cleaned
print("\n--- Cek Nilai 0 atau Null pada Kolom 'Rating' di combined_tourism_df_cleaned ---")
rating_zero_count = (combined_tourism_df_cleaned['Rating'] == 0).sum()
rating_null_count = combined_tourism_df_cleaned['Rating'].isnull().sum()

print(f"Jumlah baris dengan Rating 0: {rating_zero_count}")
print(f"Jumlah baris dengan Rating Null: {rating_null_count}")

if rating_zero_count > 0 or rating_null_count > 0:
  print("\nTerdapat nilai 0 atau Null pada kolom 'Rating'.")
  # Tampilkan baris-baris yang memiliki Rating 0 atau Null jika diinginkan
  # print("\nBaris dengan Rating 0 atau Null:")
  # print(combined_tourism_df_cleaned[combined_tourism_df_cleaned['Rating'].isnull() | (combined_tourism_df_cleaned['Rating'] == 0)])
else:
  print("\nTidak ada nilai 0 atau Null pada kolom 'Rating'.")

--- Cek Nilai 0 atau Null pada Kolom 'Rating' di combined_tourism_df_cleaned ---
Jumlah baris dengan Rating 0: 167
Jumlah baris dengan Rating Null: 0

Terdapat nilai 0 atau Null pada kolom 'Rating'.

In [13]:
combined_tourism_df_cleaned.head(5)

,Place_Id,Place_Name,Description,Category,City,Price,Rating,Time_Minutes,Lat,Long
610,611,3 WWII rusty tanks,Tempat wisata menarik di Papua,Wisata Alam,Papua,0,0.0,NaN,-2.571545,140.709192
602,603,AMA Associated Mission Aviation,Tempat wisata menarik di Papua Tengah,Wisata Alam,Papua Tengah,0,0.0,NaN,-3.366112,135.494587
453,454,Agropuro Multifarm & Outbound Adventure,Tempat wisata menarik di Riau,Wisata Petualangan,Riau,0,0.0,NaN,0.582866,101.418606
393,394,Air Mancur Menari,Jembatan Kenjeran dengan air mancur menarinya ...,Taman Hiburan,Surabaya,35000,4.4,45.0,-7.235693,112.795523
462,463,Air Panas Geragai,#SURVEYGLAM ##GLAMBANDUNG2023,Wisata Alam,Jambi,0,0.0,NaN,-1.147297,103.677157

# scraping tambahan

In [35]:
import overpy
import time

api = overpy.Overpass()

# List nama kota/provinsi yang mau di-scrape
cities = [
    "Riau",
    "Jambi",
    "Bali",
    "Papua",
    "Kalimantan Tengah",
    "Sulawesi Utara"
]

def fetch_places(city_name, limit=20):
    query = f"""
    [out:json][timeout:25];
    area["name"="{city_name}"]["admin_level"="4"]->.searchArea;

    (
      node["tourism"="attraction"](area.searchArea);
      way["tourism"="attraction"](area.searchArea);
      relation["tourism"="attraction"](area.searchArea);

      node["tourism"="museum"](area.searchArea);
      way["tourism"="museum"](area.searchArea);
      relation["tourism"="museum"](area.searchArea);

      node["leisure"="park"](area.searchArea);
      way["leisure"="park"](area.searchArea);
      relation["leisure"="park"](area.searchArea);

      node["historic"](area.searchArea);
      way["historic"](area.searchArea);
      relation["historic"](area.searchArea);
    );

    out center {limit};
    """

    try:
        result = api.query(query)
    except Exception as e:
        print(f"Error querying {city_name}: {e}")
        return []

    places = []

    for node in result.nodes:
        name = node.tags.get("name")
        if not name:
            continue
        category = node.tags.get("tourism") or node.tags.get("leisure") or node.tags.get("historic") or "N/A"
        places.append({
            "City": city_name,
            "Place_Name": name,
            "Category": category,
            "Lat": node.lat,
            "Long": node.lon
        })

    for way in result.ways:
        name = way.tags.get("name")
        if not name:
            continue
        category = way.tags.get("tourism") or way.tags.get("leisure") or way.tags.get("historic") or "N/A"
        lat = getattr(way, "center_lat", None)
        lon = getattr(way, "center_lon", None)
        if lat is None or lon is None:
            continue
        places.append({
            "City": city_name,
            "Place_Name": name,
            "Category": category,
            "Lat": lat,
            "Long": lon
        })

    return places

all_places = []

for city in cities:
    print(f"Scraping kota: {city}")
    city_places = fetch_places(city, limit=20)
    all_places.extend(city_places)
    time.sleep(2)

# Print hasil (atau bisa simpan ke CSV, DB, dll)
for place in all_places:
    print(place)

Scraping kota: Riau
Scraping kota: Jambi
Scraping kota: Bali
Scraping kota: Papua
Scraping kota: Kalimantan Tengah
Scraping kota: Sulawesi Utara
{'City': 'Riau', 'Place_Name': 'Taman Kota Bagansiapiapi', 'Category': 'park', 'Lat': Decimal('2.1620262'), 'Long': Decimal('100.8076123')}
{'City': 'Riau', 'Place_Name': 'Taman Makam Pahlawan', 'Category': 'memorial', 'Lat': Decimal('2.1612435'), 'Long': Decimal('100.8034173')}
{'City': 'Riau', 'Place_Name': 'Tugu Keris', 'Category': 'monument', 'Lat': Decimal('0.5102716'), 'Long': Decimal('101.4521183')}
{'City': 'Riau', 'Place_Name': 'Pusat Latihan Gajah Riau', 'Category': 'attraction', 'Lat': Decimal('0.7234307'), 'Long': Decimal('101.4116627')}
{'City': 'Riau', 'Place_Name': 'Tugu Bawang', 'Category': 'monument', 'Lat': Decimal('1.4914304'), 'Long': Decimal('102.0895930')}
{'City': 'Riau', 'Place_Name': 'Tugu Bambu Runcing', 'Category': 'monument', 'Lat': Decimal('0.5253175'), 'Long': Decimal('101.4526301')}
{'City': 'Riau', 'Place_Name': 'Tugu Perjuangan', 'Category': 'memorial', 'Lat': Decimal('0.5175838'), 'Long': Decimal('101.4525709')}
{'City': 'Riau', 'Place_Name': 'Museum Daerah Sang Nila Utama', 'Category': 'museum', 'Lat': Decimal('0.4942294'), 'Long': Decimal('101.4542082')}
{'City': 'Riau', 'Place_Name': 'AKHBAR SOFTWARE HOUSE', 'Category': 'monument', 'Lat': Decimal('0.4475757'), 'Long': Decimal('101.4628919')}
{'City': 'Riau', 'Place_Name': 'KUA Air Dingin', 'Category': 'museum', 'Lat': Decimal('0.4488205'), 'Long': Decimal('101.4633908')}
{'City': 'Riau', 'Place_Name': 'Tugu Perbatasan Pekanbaru', 'Category': 'monument', 'Lat': Decimal('0.4651537'), 'Long': Decimal('101.5899365')}
{'City': 'Riau', 'Place_Name': 'Tugu Perbatasan', 'Category': 'monument', 'Lat': Decimal('0.9171137'), 'Long': Decimal('102.0323603')}
{'City': 'Riau', 'Place_Name': 'Tugu Perbatasan Siak - Bengkalis', 'Category': 'monument', 'Lat': Decimal('1.1769143'), 'Long': Decimal('102.1317716')}
{'City': 'Riau', 'Place_Name': 'Tugu Batas Bantan', 'Category': 'monument', 'Lat': Decimal('1.4949532'), 'Long': Decimal('102.1424750')}
{'City': 'Riau', 'Place_Name': 'Gerbang Pantai Selat Baru', 'Category': 'monument', 'Lat': Decimal('1.5597339'), 'Long': Decimal('102.2441755')}
{'City': 'Riau', 'Place_Name': 'Taman Kota', 'Category': 'park', 'Lat': Decimal('-0.3775616'), 'Long': Decimal('102.5508412')}
{'City': 'Riau', 'Place_Name': 'Batu Hitam', 'Category': 'monument', 'Lat': Decimal('0.3268783'), 'Long': Decimal('101.0209519')}
{'City': 'Riau', 'Place_Name': 'Halte Uin SUSKA', 'Category': 'boundary_stone', 'Lat': Decimal('0.4665249'), 'Long': Decimal('101.3576411')}
{'City': 'Riau', 'Place_Name': "Ai'Home", 'Category': 'castle', 'Lat': Decimal('0.4337594'), 'Long': Decimal('101.3898907')}
{'City': 'Jambi', 'Place_Name': 'Simpang Bambu Kuning', 'Category': 'wayside_cross', 'Lat': Decimal('-1.4837128'), 'Long': Decimal('102.1142892')}
{'City': 'Jambi', 'Place_Name': 'Air Panas Semurup', 'Category': 'attraction', 'Lat': Decimal('-1.9882085'), 'Long': Decimal('101.3576773')}
{'City': 'Jambi', 'Place_Name': 'Jam Gento Bangko', 'Category': 'attraction', 'Lat': Decimal('-2.0763467'), 'Long': Decimal('102.2744630')}
{'City': 'Jambi', 'Place_Name': 'Tugu Ikan', 'Category': 'memorial', 'Lat': Decimal('-1.5563122'), 'Long': Decimal('102.1791467')}
{'City': 'Jambi', 'Place_Name': 'Kompleks Percandian Muaro Jambi', 'Category': 'archaeological_site', 'Lat': Decimal('-1.4765026'), 'Long': Decimal('103.6681402')}
{'City': 'Jambi', 'Place_Name': 'Tugu Bundaran Simpang Dado Pasar Buah Kota Jambi', 'Category': 'monument', 'Lat': Decimal('-1.5932203'), 'Long': Decimal('103.6171043')}
{'City': 'Jambi', 'Place_Name': 'Taman Pkk Thehok The Hok', 'Category': 'park', 'Lat': Decimal('-1.6167963'), 'Long': Decimal('103.6283126')}
{'City': 'Jambi', 'Place_Name': 'Kantor Desa Lagan Tengah', 'Category': 'park', 'Lat': Decimal('-1.0876136'), 'Long': Decimal('103.7274798')}
{'City': 'Jambi', 'Place_Name': 'taman budaya jambu', 'Category': 'park', 'Lat': Decimal('-1.6147010'), 'Long': Decimal('103.5853664')}
{'City': 'Jambi', 'Place_Name': 'Candi Sialang', 'Category': 'archaeological_site', 'Lat': Decimal('-1.4684908'), 'Long': Decimal('103.6812910')}
{'City': 'Jambi', 'Place_Name': 'Menapo', 'Category': 'ruins', 'Lat': Decimal('-1.4674022'), 'Long': Decimal('103.6822030')}
{'City': 'Jambi', 'Place_Name': 'Menapo', 'Category': 'ruins', 'Lat': Decimal('-1.4668766'), 'Long': Decimal('103.6799419')}
{'City': 'Jambi', 'Place_Name': 'Menapo', 'Category': 'ruins', 'Lat': Decimal('-1.4674129'), 'Long': Decimal('103.6797622')}
{'City': 'Jambi', 'Place_Name': 'Menapo', 'Category': 'ruins', 'Lat': Decimal('-1.4684238'), 'Long': Decimal('103.6799231')}
{'City': 'Bali', 'Place_Name': 'Margarana Memorial', 'Category': 'memorial', 'Lat': Decimal('-8.4650283'), 'Long': Decimal('115.1637938')}
{'City': 'Bali', 'Place_Name': 'Bali Butterfly Park', 'Category': 'attraction', 'Lat': Decimal('-8.4794589'), 'Long': Decimal('115.1346292')}
{'City': 'Bali', 'Place_Name': 'Museum Subak', 'Category': 'museum', 'Lat': Decimal('-8.5444662'), 'Long': Decimal('115.1384002')}
{'City': 'Bali', 'Place_Name': 'Paintball', 'Category': 'attraction', 'Lat': Decimal('-8.8177858'), 'Long': Decimal('115.1638782')}
{'City': 'Bali', 'Place_Name': 'Pura Luhur Batukaru', 'Category': 'monument', 'Lat': Decimal('-8.3726461'), 'Long': Decimal('115.1027505')}
{'City': 'Bali', 'Place_Name': 'Pura Susunan Wadonan', 'Category': 'attraction', 'Lat': Decimal('-8.7401106'), 'Long': Decimal('115.2371004')}
{'City': 'Bali', 'Place_Name': 'Museum Purbakala', 'Category': 'museum', 'Lat': Decimal('-8.5119445'), 'Long': Decimal('115.2997459')}
{'City': 'Bali', 'Place_Name': 'Makam Jayaprana', 'Category': 'memorial', 'Lat': Decimal('-8.1555791'), 'Long': Decimal('114.5407810')}
{'City': 'Bali', 'Place_Name': 'Museum Situs Purbakala', 'Category': 'museum', 'Lat': Decimal('-8.1673086'), 'Long': Decimal('114.4406786')}
{'City': 'Bali', 'Place_Name': 'Tenganan Pegringsingan', 'Category': 'attraction', 'Lat': Decimal('-8.4746834'), 'Long': Decimal('115.5666957')}
{'City': 'Bali', 'Place_Name': 'Shiva temple', 'Category': 'monument', 'Lat': Decimal('-8.3281131'), 'Long': Decimal('115.0653981')}
{'City': 'Bali', 'Place_Name': 'Tegenungan Blangsinga', 'Category': 'attraction', 'Lat': Decimal('-8.5752294'), 'Long': Decimal('115.2907014')}
{'City': 'Bali', 'Place_Name': 'Brahma Arama Vihara', 'Category': 'monument', 'Lat': Decimal('-8.2112910'), 'Long': Decimal('114.9742510')}
{'City': 'Bali', 'Place_Name': 'Pura Ulun Danu Batur', 'Category': 'monument', 'Lat': Decimal('-8.2567155'), 'Long': Decimal('115.3386308')}
{'City': 'Bali', 'Place_Name': 'Pura Ibu Bendesa Basangalas', 'Category': 'monument', 'Lat': Decimal('-8.3979121'), 'Long': Decimal('115.6183355')}
{'City': 'Bali', 'Place_Name': 'Pura Puseh Desa Adat Basangalas', 'Category': 'monument', 'Lat': Decimal('-8.3974981'), 'Long': Decimal('115.6180351')}
{'City': 'Bali', 'Place_Name': 'Pura Batu Kolok (temple)', 'Category': 'monument', 'Lat': Decimal('-8.5766202'), 'Long': Decimal('115.4006899')}
{'City': 'Bali', 'Place_Name': 'Pura Masceti (temple)', 'Category': 'monument', 'Lat': Decimal('-8.5955778'), 'Long': Decimal('115.3423786')}
{'City': 'Papua', 'Place_Name': 'Mac Arthur Site', 'Category': 'memorial', 'Lat': Decimal('-2.5633370'), 'Long': Decimal('140.5435293')}
{'City': 'Papua', 'Place_Name': 'Tugu Salib', 'Category': 'memorial', 'Lat': Decimal('-2.5654216'), 'Long': Decimal('140.4118979')}
{'City': 'Papua', 'Place_Name': 'Kalibiru', 'Category': 'park', 'Lat': Decimal('-2.5145278'), 'Long': Decimal('140.1454677')}
{'City': 'Papua', 'Place_Name': 'Museum Lokabudaya Uncen', 'Category': 'museum', 'Lat': Decimal('-2.6104677'), 'Long': Decimal('140.6604184')}
{'City': 'Papua', 'Place_Name': 'Situs Megalitik Tutari', 'Category': 'archaeological_site', 'Lat': Decimal('-2.5686470'), 'Long': Decimal('140.4538452')}
{'City': 'Papua', 'Place_Name': 'Tugu Serui', 'Category': 'monument', 'Lat': Decimal('-1.8861398'), 'Long': Decimal('136.2431008')}
{'City': 'Papua', 'Place_Name': 'Batupapan, rock layers beack', 'Category': 'attraction', 'Lat': Decimal('-2.2053977'), 'Long': Decimal('136.4217401')}
{'City': 'Papua', 'Place_Name': 'Danger Waves Sign!', 'Category': 'attraction', 'Lat': Decimal('-1.8902681'), 'Long': Decimal('136.2391831')}
{'City': 'Papua', 'Place_Name': 'Small Sea Village', 'Category': 'attraction', 'Lat': Decimal('-1.8922710'), 'Long': Decimal('136.2375262')}
{'City': 'Papua', 'Place_Name': 'Waves escape sign!', 'Category': 'attraction', 'Lat': Decimal('-1.8917206'), 'Long': Decimal('136.2368703')}
{'City': 'Papua', 'Place_Name': 'Pigeons Holes, actual pigeons', 'Category': 'attraction', 'Lat': Decimal('-1.8906527'), 'Long': Decimal('136.2376583')}
{'City': 'Papua', 'Place_Name': 'Crafts, mini row boats, Traditional Snake Drums', 'Category': 'attraction', 'Lat': Decimal('-1.8909602'), 'Long': Decimal('136.2374733')}
{'City': 'Papua', 'Place_Name': 'Old WWII plane hangars converted into houses', 'Category': 'attraction', 'Lat': Decimal('-1.1830739'), 'Long': Decimal('136.0780758')}
{'City': 'Papua', 'Place_Name': 'Wandos Mangled Forested Boat Beach', 'Category': 'attraction', 'Lat': Decimal('-0.7127577'), 'Long': Decimal('135.7870431')}
{'City': 'Papua', 'Place_Name': 'Coconuts beach', 'Category': 'attraction', 'Lat': Decimal('-0.6900469'), 'Long': Decimal('135.8259402')}
{'City': 'Papua', 'Place_Name': 'Beautiful Small Coconuts  Bay', 'Category': 'attraction', 'Lat': Decimal('-0.8145005'), 'Long': Decimal('135.9781691')}
{'City': 'Papua', 'Place_Name': 'Marluia peninsula ', 'Category': 'attraction', 'Lat': Decimal('-0.8226892'), 'Long': Decimal('135.9997010')}
{'City': 'Papua', 'Place_Name': 'Traditional house', 'Category': 'attraction', 'Lat': Decimal('-0.8345133'), 'Long': Decimal('135.9563033')}
{'City': 'Papua', 'Place_Name': 'Rock mountain on the beach, giant coconut crabs here', 'Category': 'attraction', 'Lat': Decimal('-0.6923431'), 'Long': Decimal('135.8310478')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Tugu Burung Enggang Pasar Panas Perbatasan Kalsel-Kalteng', 'Category': 'monument', 'Lat': Decimal('-2.1982417'), 'Long': Decimal('115.2402817')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Museum Lewu Hante', 'Category': 'museum', 'Lat': Decimal('-2.1986437'), 'Long': Decimal('115.2401583')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Tugu Selamat Datang Barito Timur', 'Category': 'memorial', 'Lat': Decimal('-2.2260152'), 'Long': Decimal('115.2648181')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Feeding Cam Lakey', 'Category': 'attraction', 'Lat': Decimal('-2.7650718'), 'Long': Decimal('111.9529234')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Tugu Proklamasi', 'Category': 'monument', 'Lat': Decimal('-2.5393186'), 'Long': Decimal('112.9589852')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Cagar Budaya Putri Mayang', 'Category': 'archaeological_site', 'Lat': Decimal('-2.1411232'), 'Long': Decimal('115.2042793')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Akasia', 'Category': 'park', 'Lat': Decimal('-2.5675387'), 'Long': Decimal('112.9480787')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Bundaran PEMDA', 'Category': 'monument', 'Lat': Decimal('-2.5386912'), 'Long': Decimal('112.9418230')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Feeding Pondok Tangui', 'Category': 'attraction', 'Lat': Decimal('-2.7942353'), 'Long': Decimal('111.8821314')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Tanjung Harapan', 'Category': 'attraction', 'Lat': Decimal('-2.8331522'), 'Long': Decimal('111.7980790')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'POHON SAWIT', 'Category': 'park', 'Lat': Decimal('-2.5386192'), 'Long': Decimal('112.9460682')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Yayasan Orang Utan Internasional', 'Category': 'park', 'Lat': Decimal('-2.7299299'), 'Long': Decimal('111.6482277')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Tugu Bundaran KB', 'Category': 'monument', 'Lat': Decimal('-2.5704992'), 'Long': Decimal('112.9505133')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Batas Waktu Feeding Station', 'Category': 'attraction', 'Lat': Decimal('-2.8232578'), 'Long': Decimal('111.8099666')}
{'City': 'Kalimantan Tengah', 'Place_Name': "Tam'mak Bugawan Dime", 'Category': 'archaeological_site', 'Lat': Decimal('-2.0502452'), 'Long': Decimal('115.0487222')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Tugu Rusa', 'Category': 'memorial', 'Lat': Decimal('-2.1844249'), 'Long': Decimal('111.4289658')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Night walk', 'Category': 'attraction', 'Lat': Decimal('-2.7409451'), 'Long': Decimal('111.9193936')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Tugu Adipura', 'Category': 'monument', 'Lat': Decimal('-3.0014137'), 'Long': Decimal('114.3915779')}
{'City': 'Kalimantan Tengah', 'Place_Name': 'Istana Isen Mulang', 'Category': 'manor', 'Lat': Decimal('-2.2061633'), 'Long': Decimal('113.9186311')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Zero Point', 'Category': 'boundary_stone', 'Lat': Decimal('1.4907421'), 'Long': Decimal('124.8390995')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Toar Lummimuut', 'Category': 'monument', 'Lat': Decimal('1.4864771'), 'Long': Decimal('124.8511822')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Walanda Maramis', 'Category': 'monument', 'Lat': Decimal('1.4886102'), 'Long': Decimal('124.8480029')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Yesus Memberkati', 'Category': 'monument', 'Lat': Decimal('1.4381551'), 'Long': Decimal('124.8477673')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Kantor Sinode GMIM', 'Category': 'attraction', 'Lat': Decimal('1.3347564'), 'Long': Decimal('124.8374226')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Auditorium Bukit Inspirasi', 'Category': 'attraction', 'Lat': Decimal('1.3378463'), 'Long': Decimal('124.8377960')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Hot springs', 'Category': 'attraction', 'Lat': Decimal('1.1668971'), 'Long': Decimal('124.8207836')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Japanese Cave', 'Category': 'attraction', 'Lat': Decimal('1.2041396'), 'Long': Decimal('124.8075258')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Japanese Cave', 'Category': 'attraction', 'Lat': Decimal('1.3269041'), 'Long': Decimal('124.9252742')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Waruga cemetry', 'Category': 'memorial', 'Lat': Decimal('1.3205022'), 'Long': Decimal('124.8103822')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Watu Pinabetengan', 'Category': 'memorial', 'Lat': Decimal('1.1592760'), 'Long': Decimal('124.7713008')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Benteng Moraya', 'Category': 'monument', 'Lat': Decimal('1.2904077'), 'Long': Decimal('124.9091760')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Wooden House Factory', 'Category': 'attraction', 'Lat': Decimal('1.3183539'), 'Long': Decimal('124.8218999')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Gua Japeng', 'Category': 'yes', 'Lat': Decimal('1.3307129'), 'Long': Decimal('124.8078693')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Monumen Tua Lokon Pinontoan Kayawu', 'Category': 'memorial', 'Lat': Decimal('1.3308899'), 'Long': Decimal('124.8078049')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Monumen Lilin', 'Category': 'monument', 'Lat': Decimal('1.4944640'), 'Long': Decimal('124.8382842')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Tugu Adipura', 'Category': 'monument', 'Lat': Decimal('1.5282457'), 'Long': Decimal('124.9209754')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Tugu Peringatan Worang', 'Category': 'memorial', 'Lat': Decimal('1.4921288'), 'Long': Decimal('124.8396771')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Tugu Jam', 'Category': 'memorial', 'Lat': Decimal('1.4443533'), 'Long': Decimal('125.1904451')}
{'City': 'Sulawesi Utara', 'Place_Name': 'Tugu Ibukota Kabupaten', 'Category': 'monument', 'Lat': Decimal('3.9994517'), 'Long': Decimal('126.6777875')}

In [37]:
df = pd.DataFrame(all_places)
df.to_csv("wisata_indonesia_osm.csv", index=False)
print("Selesai simpan data ke wisata_indonesia_osm.csv")

Selesai simpan data ke wisata_indonesia_osm.csv

In [39]:
import pandas as pd
import requests
import time

def get_wikipedia_summary_id(place_name):
    """
    Ambil ringkasan dari Wikipedia bahasa Indonesia berdasarkan nama tempat.
    """
    url = f"https://id.wikipedia.org/api/rest_v1/page/summary/{place_name.replace(' ', '_')}"
    try:
        res = requests.get(url)
        if res.status_code == 200:
            data = res.json()
            if 'extract' in data:
                return data['extract']
            else:
                return None
        else:
            return None
    except Exception as e:
        return None

# Load CSV
df = pd.read_csv("/content/wisata_indonesia_osm.csv")

# Cek ada kolom Description belum, kalau belum buat
if 'Description' not in df.columns:
    df['Description'] = None

# Loop tiap tempat wisata, update kolom Description
for i, row in df.iterrows():
    place = row['Place_Name']
    print(f"Mencari deskripsi: {place} ({i+1}/{len(df)})")

    desc = get_wikipedia_summary_id(place)
    if desc:
        df.at[i, 'Description'] = desc
        print(f"Deskripsi ditemukan untuk {place}")
    else:
        print(f"Deskripsi tidak ditemukan untuk {place}")

    time.sleep(1)  # Untuk menghindari limit request API Wikipedia

# Simpan CSV hasil update
df.to_csv("wisata_indonesia_osm_updated.csv", index=False)
print("Selesai update deskripsi ke CSV.")

Mencari deskripsi: Taman Kota Bagansiapiapi (1/109)
Deskripsi tidak ditemukan untuk Taman Kota Bagansiapiapi
Mencari deskripsi: Taman Makam Pahlawan (2/109)
Deskripsi ditemukan untuk Taman Makam Pahlawan
Mencari deskripsi: Tugu Keris (3/109)
Deskripsi tidak ditemukan untuk Tugu Keris
Mencari deskripsi: Pusat Latihan Gajah Riau (4/109)
Deskripsi tidak ditemukan untuk Pusat Latihan Gajah Riau
Mencari deskripsi: Tugu Bawang (5/109)
Deskripsi tidak ditemukan untuk Tugu Bawang
Mencari deskripsi: Tugu Bambu Runcing (6/109)
Deskripsi tidak ditemukan untuk Tugu Bambu Runcing
Mencari deskripsi: Tugu Perjuangan (7/109)
Deskripsi tidak ditemukan untuk Tugu Perjuangan
Mencari deskripsi: Museum Daerah Sang Nila Utama (8/109)
Deskripsi tidak ditemukan untuk Museum Daerah Sang Nila Utama
Mencari deskripsi: AKHBAR SOFTWARE HOUSE (9/109)
Deskripsi tidak ditemukan untuk AKHBAR SOFTWARE HOUSE
Mencari deskripsi: KUA Air Dingin (10/109)
Deskripsi tidak ditemukan untuk KUA Air Dingin
Mencari deskripsi: Tugu Perbatasan Pekanbaru (11/109)
Deskripsi tidak ditemukan untuk Tugu Perbatasan Pekanbaru
Mencari deskripsi: Tugu Perbatasan (12/109)
Deskripsi tidak ditemukan untuk Tugu Perbatasan
Mencari deskripsi: Tugu Perbatasan Siak - Bengkalis (13/109)
Deskripsi tidak ditemukan untuk Tugu Perbatasan Siak - Bengkalis
Mencari deskripsi: Tugu Batas Bantan (14/109)
Deskripsi tidak ditemukan untuk Tugu Batas Bantan
Mencari deskripsi: Gerbang Pantai Selat Baru (15/109)
Deskripsi tidak ditemukan untuk Gerbang Pantai Selat Baru
Mencari deskripsi: Taman Kota (16/109)
Deskripsi tidak ditemukan untuk Taman Kota
Mencari deskripsi: Batu Hitam (17/109)
Deskripsi tidak ditemukan untuk Batu Hitam
Mencari deskripsi: Halte Uin SUSKA (18/109)
Deskripsi tidak ditemukan untuk Halte Uin SUSKA
Mencari deskripsi: Ai'Home (19/109)
Deskripsi tidak ditemukan untuk Ai'Home
Mencari deskripsi: Simpang Bambu Kuning (20/109)
Deskripsi tidak ditemukan untuk Simpang Bambu Kuning
Mencari deskripsi: Air Panas Semurup (21/109)
Deskripsi ditemukan untuk Air Panas Semurup
Mencari deskripsi: Jam Gento Bangko (22/109)
Deskripsi tidak ditemukan untuk Jam Gento Bangko
Mencari deskripsi: Tugu Ikan (23/109)
Deskripsi tidak ditemukan untuk Tugu Ikan
Mencari deskripsi: Kompleks Percandian Muaro Jambi (24/109)
Deskripsi tidak ditemukan untuk Kompleks Percandian Muaro Jambi
Mencari deskripsi: Tugu Bundaran Simpang Dado Pasar Buah Kota Jambi (25/109)
Deskripsi tidak ditemukan untuk Tugu Bundaran Simpang Dado Pasar Buah Kota Jambi
Mencari deskripsi: Taman Pkk Thehok The Hok (26/109)
Deskripsi tidak ditemukan untuk Taman Pkk Thehok The Hok
Mencari deskripsi: Kantor Desa Lagan Tengah (27/109)
Deskripsi tidak ditemukan untuk Kantor Desa Lagan Tengah
Mencari deskripsi: taman budaya jambu (28/109)
Deskripsi tidak ditemukan untuk taman budaya jambu
Mencari deskripsi: Candi Sialang (29/109)
Deskripsi tidak ditemukan untuk Candi Sialang
Mencari deskripsi: Menapo (30/109)
Deskripsi tidak ditemukan untuk Menapo
Mencari deskripsi: Menapo (31/109)
Deskripsi tidak ditemukan untuk Menapo
Mencari deskripsi: Menapo (32/109)
Deskripsi tidak ditemukan untuk Menapo
Mencari deskripsi: Menapo (33/109)
Deskripsi tidak ditemukan untuk Menapo
Mencari deskripsi: Margarana Memorial (34/109)
Deskripsi tidak ditemukan untuk Margarana Memorial
Mencari deskripsi: Bali Butterfly Park (35/109)
Deskripsi tidak ditemukan untuk Bali Butterfly Park
Mencari deskripsi: Museum Subak (36/109)
Deskripsi ditemukan untuk Museum Subak
Mencari deskripsi: Paintball (37/109)
Deskripsi tidak ditemukan untuk Paintball
Mencari deskripsi: Pura Luhur Batukaru (38/109)
Deskripsi ditemukan untuk Pura Luhur Batukaru
Mencari deskripsi: Pura Susunan Wadonan (39/109)
Deskripsi tidak ditemukan untuk Pura Susunan Wadonan
Mencari deskripsi: Museum Purbakala (40/109)
Deskripsi tidak ditemukan untuk Museum Purbakala
Mencari deskripsi: Makam Jayaprana (41/109)
Deskripsi tidak ditemukan untuk Makam Jayaprana
Mencari deskripsi: Museum Situs Purbakala (42/109)
Deskripsi tidak ditemukan untuk Museum Situs Purbakala
Mencari deskripsi: Tenganan Pegringsingan (43/109)
Deskripsi tidak ditemukan untuk Tenganan Pegringsingan
Mencari deskripsi: Shiva temple (44/109)
Deskripsi tidak ditemukan untuk Shiva temple
Mencari deskripsi: Tegenungan Blangsinga (45/109)
Deskripsi tidak ditemukan untuk Tegenungan Blangsinga
Mencari deskripsi: Brahma Arama Vihara (46/109)
Deskripsi tidak ditemukan untuk Brahma Arama Vihara
Mencari deskripsi: Pura Ulun Danu Batur (47/109)
Deskripsi ditemukan untuk Pura Ulun Danu Batur
Mencari deskripsi: Pura Ibu Bendesa Basangalas (48/109)
Deskripsi tidak ditemukan untuk Pura Ibu Bendesa Basangalas
Mencari deskripsi: Pura Puseh Desa Adat Basangalas (49/109)
Deskripsi tidak ditemukan untuk Pura Puseh Desa Adat Basangalas
Mencari deskripsi: Pura Batu Kolok (temple) (50/109)
Deskripsi tidak ditemukan untuk Pura Batu Kolok (temple)
Mencari deskripsi: Pura Masceti (temple) (51/109)
Deskripsi tidak ditemukan untuk Pura Masceti (temple)
Mencari deskripsi: Mac Arthur Site (52/109)
Deskripsi tidak ditemukan untuk Mac Arthur Site
Mencari deskripsi: Tugu Salib (53/109)
Deskripsi tidak ditemukan untuk Tugu Salib
Mencari deskripsi: Kalibiru (54/109)
Deskripsi ditemukan untuk Kalibiru
Mencari deskripsi: Museum Lokabudaya Uncen (55/109)
Deskripsi tidak ditemukan untuk Museum Lokabudaya Uncen
Mencari deskripsi: Situs Megalitik Tutari (56/109)
Deskripsi tidak ditemukan untuk Situs Megalitik Tutari
Mencari deskripsi: Tugu Serui (57/109)
Deskripsi tidak ditemukan untuk Tugu Serui
Mencari deskripsi: Batupapan, rock layers beack (58/109)
Deskripsi tidak ditemukan untuk Batupapan, rock layers beack
Mencari deskripsi: Danger Waves Sign! (59/109)
Deskripsi tidak ditemukan untuk Danger Waves Sign!
Mencari deskripsi: Small Sea Village (60/109)
Deskripsi tidak ditemukan untuk Small Sea Village
Mencari deskripsi: Waves escape sign! (61/109)
Deskripsi tidak ditemukan untuk Waves escape sign!
Mencari deskripsi: Pigeons Holes, actual pigeons (62/109)
Deskripsi tidak ditemukan untuk Pigeons Holes, actual pigeons
Mencari deskripsi: Crafts, mini row boats, Traditional Snake Drums (63/109)
Deskripsi tidak ditemukan untuk Crafts, mini row boats, Traditional Snake Drums
Mencari deskripsi: Old WWII plane hangars converted into houses (64/109)
Deskripsi tidak ditemukan untuk Old WWII plane hangars converted into houses
Mencari deskripsi: Wandos Mangled Forested Boat Beach (65/109)
Deskripsi tidak ditemukan untuk Wandos Mangled Forested Boat Beach
Mencari deskripsi: Coconuts beach (66/109)
Deskripsi tidak ditemukan untuk Coconuts beach
Mencari deskripsi: Beautiful Small Coconuts  Bay (67/109)
Deskripsi tidak ditemukan untuk Beautiful Small Coconuts  Bay
Mencari deskripsi: Marluia peninsula  (68/109)
Deskripsi tidak ditemukan untuk Marluia peninsula
Mencari deskripsi: Traditional house (69/109)
Deskripsi tidak ditemukan untuk Traditional house
Mencari deskripsi: Rock mountain on the beach, giant coconut crabs here (70/109)
Deskripsi tidak ditemukan untuk Rock mountain on the beach, giant coconut crabs here
Mencari deskripsi: Tugu Burung Enggang Pasar Panas Perbatasan Kalsel-Kalteng (71/109)
Deskripsi tidak ditemukan untuk Tugu Burung Enggang Pasar Panas Perbatasan Kalsel-Kalteng
Mencari deskripsi: Museum Lewu Hante (72/109)
Deskripsi ditemukan untuk Museum Lewu Hante
Mencari deskripsi: Tugu Selamat Datang Barito Timur (73/109)
Deskripsi tidak ditemukan untuk Tugu Selamat Datang Barito Timur
Mencari deskripsi: Feeding Cam Lakey (74/109)
Deskripsi tidak ditemukan untuk Feeding Cam Lakey
Mencari deskripsi: Tugu Proklamasi (75/109)
Deskripsi ditemukan untuk Tugu Proklamasi
Mencari deskripsi: Cagar Budaya Putri Mayang (76/109)
Deskripsi tidak ditemukan untuk Cagar Budaya Putri Mayang
Mencari deskripsi: Akasia (77/109)
Deskripsi ditemukan untuk Akasia
Mencari deskripsi: Bundaran PEMDA (78/109)
Deskripsi tidak ditemukan untuk Bundaran PEMDA
Mencari deskripsi: Feeding Pondok Tangui (79/109)
Deskripsi tidak ditemukan untuk Feeding Pondok Tangui
Mencari deskripsi: Tanjung Harapan (80/109)
Deskripsi ditemukan untuk Tanjung Harapan
Mencari deskripsi: POHON SAWIT (81/109)
Deskripsi tidak ditemukan untuk POHON SAWIT
Mencari deskripsi: Yayasan Orang Utan Internasional (82/109)
Deskripsi tidak ditemukan untuk Yayasan Orang Utan Internasional
Mencari deskripsi: Tugu Bundaran KB (83/109)
Deskripsi tidak ditemukan untuk Tugu Bundaran KB
Mencari deskripsi: Batas Waktu Feeding Station (84/109)
Deskripsi tidak ditemukan untuk Batas Waktu Feeding Station
Mencari deskripsi: Tam'mak Bugawan Dime (85/109)
Deskripsi tidak ditemukan untuk Tam'mak Bugawan Dime
Mencari deskripsi: Tugu Rusa (86/109)
Deskripsi tidak ditemukan untuk Tugu Rusa
Mencari deskripsi: Night walk (87/109)
Deskripsi tidak ditemukan untuk Night walk
Mencari deskripsi: Tugu Adipura (88/109)
Deskripsi ditemukan untuk Tugu Adipura
Mencari deskripsi: Istana Isen Mulang (89/109)
Deskripsi tidak ditemukan untuk Istana Isen Mulang
Mencari deskripsi: Zero Point (90/109)
Deskripsi tidak ditemukan untuk Zero Point
Mencari deskripsi: Toar Lummimuut (91/109)
Deskripsi tidak ditemukan untuk Toar Lummimuut
Mencari deskripsi: Walanda Maramis (92/109)
Deskripsi ditemukan untuk Walanda Maramis
Mencari deskripsi: Yesus Memberkati (93/109)
Deskripsi tidak ditemukan untuk Yesus Memberkati
Mencari deskripsi: Kantor Sinode GMIM (94/109)
Deskripsi tidak ditemukan untuk Kantor Sinode GMIM
Mencari deskripsi: Auditorium Bukit Inspirasi (95/109)
Deskripsi tidak ditemukan untuk Auditorium Bukit Inspirasi
Mencari deskripsi: Hot springs (96/109)
Deskripsi tidak ditemukan untuk Hot springs
Mencari deskripsi: Japanese Cave (97/109)
Deskripsi tidak ditemukan untuk Japanese Cave
Mencari deskripsi: Japanese Cave (98/109)
Deskripsi tidak ditemukan untuk Japanese Cave
Mencari deskripsi: Waruga cemetry (99/109)
Deskripsi tidak ditemukan untuk Waruga cemetry
Mencari deskripsi: Watu Pinabetengan (100/109)
Deskripsi tidak ditemukan untuk Watu Pinabetengan
Mencari deskripsi: Benteng Moraya (101/109)
Deskripsi tidak ditemukan untuk Benteng Moraya
Mencari deskripsi: Wooden House Factory (102/109)
Deskripsi tidak ditemukan untuk Wooden House Factory
Mencari deskripsi: Gua Japeng (103/109)
Deskripsi tidak ditemukan untuk Gua Japeng
Mencari deskripsi: Monumen Tua Lokon Pinontoan Kayawu (104/109)
Deskripsi tidak ditemukan untuk Monumen Tua Lokon Pinontoan Kayawu
Mencari deskripsi: Monumen Lilin (105/109)
Deskripsi tidak ditemukan untuk Monumen Lilin
Mencari deskripsi: Tugu Adipura (106/109)
Deskripsi ditemukan untuk Tugu Adipura
Mencari deskripsi: Tugu Peringatan Worang (107/109)
Deskripsi tidak ditemukan untuk Tugu Peringatan Worang
Mencari deskripsi: Tugu Jam (108/109)
Deskripsi tidak ditemukan untuk Tugu Jam
Mencari deskripsi: Tugu Ibukota Kabupaten (109/109)
Deskripsi tidak ditemukan untuk Tugu Ibukota Kabupaten
Selesai update deskripsi ke CSV.

In [41]:
pip install wikipedia-api

Collecting wikipedia-api
  Downloading wikipedia_api-0.8.1.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from wikipedia-api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->wikipedia-api) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->wikipedia-api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->wikipedia-api) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->wikipedia-api) (2025.4.26)
Building wheels for collected packages: wikipedia-api
  Building wheel for wikipedia-api (setup.py) ... done
  Created wheel for wikipedia-api: filename=Wikipedia_API-0.8.1-py3-none-any.whl size=15383 sha256=d4a80ae078d92f970201a759e41804f92ac69b31d41d76ea74d52430e32567b9
  Stored in directory: /root/.cache/pip/wheels/0b/0f/39/e8214ec038ccd5aeb8c82b957289f2f3ab2251febeae5c2860
Successfully built wikipedia-api
Installing collected packages: wikipedia-api
Successfully installed wikipedia-api-0.8.1

In [55]:
# Instalasi library yang diperlukan
# !pip install requests beautifulsoup4 googlemaps selenium pandas numpy

import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import re

def scrape_wikipedia_description(place_name):
    """
    Fungsi sederhana untuk mendapatkan deskripsi dari Wikipedia Indonesia
    """
    try:
        # Bersihkan nama tempat untuk URL
        clean_name = place_name.replace(" ", "_")

        # Coba akses langsung halaman Wikipedia
        wiki_url = f"https://id.wikipedia.org/wiki/{clean_name}"
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }

        response = requests.get(wiki_url, headers=headers)

        if response.status_code == 200:
            soup = BeautifulSoup(response.content, 'html.parser')

            # Cari paragraf pertama
            content_div = soup.find('div', {'id': 'mw-content-text'})
            if content_div:
                paragraphs = content_div.find_all('p')
                for p in paragraphs:
                    text = p.get_text(strip=True)
                    if len(text) > 50:  # Minimal 50 karakter
                        return text[:500]  # Batasi 500 karakter

        # Jika tidak berhasil, coba menggunakan API pencarian
        search_url = "https://id.wikipedia.org/w/api.php"
        params = {
            'action': 'query',
            'format': 'json',
            'list': 'search',
            'srsearch': place_name,
            'srlimit': 1
        }

        response = requests.get(search_url, params=params)
        if response.status_code == 200:
            data = response.json()
            if data['query']['search']:
                title = data['query']['search'][0]['title']
                snippet = data['query']['search'][0]['snippet']
                # Bersihkan HTML tags dari snippet
                clean_snippet = re.sub('<.*?>', '', snippet)
                return clean_snippet

    except Exception as e:
        print(f"Error scraping Wikipedia for {place_name}: {e}")

    return None

def generate_simple_description(place_name, category, city):
    """
    Generate deskripsi sederhana berdasarkan kategori dan lokasi
    """
    category_descriptions = {
        'park': f"{place_name} adalah sebuah taman yang terletak di {city}. Tempat ini menyediakan ruang hijau untuk rekreasi dan bersantai bagi masyarakat.",
        'memorial': f"{place_name} adalah monumen peringatan yang berlokasi di {city}. Tempat ini memiliki nilai sejarah dan budaya yang penting.",
        'monument': f"{place_name} adalah sebuah monumen bersejarah di {city}. Bangunan ini menjadi landmark dan memiliki nilai historis.",
        'attraction': f"{place_name} adalah objek wisata menarik yang terletak di {city}. Tempat ini menawarkan pengalaman unik bagi pengunjung.",
        'museum': f"{place_name} adalah museum yang berlokasi di {city}. Tempat ini menyimpan koleksi dan informasi penting tentang sejarah dan budaya.",
        'temple': f"{place_name} adalah tempat ibadah yang terletak di {city}. Bangunan ini memiliki nilai spiritual dan arsitektur yang menarik.",
        'beach': f"{place_name} adalah pantai yang terletak di {city}. Tempat ini menawarkan pemandangan laut dan aktivitas wisata bahari."
    }

    return category_descriptions.get(category.lower(),
        f"{place_name} adalah tempat wisata yang terletak di {city}. Destinasi ini menawarkan pengalaman menarik bagi para pengunjung.")

# Fungsi utama untuk memproses dataframe
def enhance_tourism_data(df_path, output_path):
    """
    Fungsi utama untuk melengkapi data wisata
    """
    # Load data
    df = pd.read_csv(df_path)

    print(f"Loaded {len(df)} records")

    # Tambah kolom Rating jika belum ada
    if 'Rating' not in df.columns:
        df['Rating'] = None

    # Counter untuk tracking
    updated_count = 0

    for idx, row in df.iterrows():
        place_name = row['Place_Name']
        city = row['City']
        category = row['Category']
        current_desc = row['Description']

        print(f"Processing {idx+1}/{len(df)}: {place_name}")

        # Skip jika sudah ada deskripsi yang cukup panjang
        if pd.notna(current_desc) and len(str(current_desc)) > 50:
            print(f"  -> Already has description")
            continue

        # Coba dapatkan dari Wikipedia
        wiki_desc = scrape_wikipedia_description(place_name)

        if wiki_desc:
            df.at[idx, 'Description'] = wiki_desc
            print(f"  -> Updated from Wikipedia")
            updated_count += 1
        else:
            # Jika tidak ada di Wikipedia, buat deskripsi sederhana
            simple_desc = generate_simple_description(place_name, category, city)
            df.at[idx, 'Description'] = simple_desc
            print(f"  -> Generated simple description")
            updated_count += 1

        # Rating dummy (bisa diganti dengan scraping nyata)
        if pd.isna(row['Rating']):
            df.at[idx, 'Rating'] = round(3.5 + (hash(place_name) % 15) / 10, 1)  # Rating 3.5-5.0

        # Delay untuk menghindari rate limiting
        time.sleep(0.5)

        # Save progress setiap 50 record
        if (idx + 1) % 50 == 0:
            df.to_csv(output_path, index=False)
            print(f"  -> Progress saved at {idx+1} records")

    # Save final result
    df.to_csv(output_path, index=False)

    print(f"\nCompleted!")
    print(f"Updated {updated_count} descriptions")
    print(f"Results saved to {output_path}")

    return df

# Contoh penggunaan
if __name__ == "__main__":
    # Ganti path sesuai dengan lokasi file Anda
    input_file = "/content/wisata_indonesia_osm_updated.csv"
    output_file = "/content/wisata_indonesia_enhanced.csv"

    # Proses data
    enhanced_df = enhance_tourism_data(input_file, output_file)

    # Tampilkan sample hasil
    print("\nSample results:")
    print(enhanced_df[['Place_Name', 'City', 'Description', 'Rating']].head())

    # Statistik
    print(f"\nStatistics:")
    print(f"Total records: {len(enhanced_df)}")
    print(f"Records with description: {enhanced_df['Description'].notna().sum()}")
    print(f"Records with rating: {enhanced_df['Rating'].notna().sum()}")
    print(f"Average rating: {enhanced_df['Rating'].mean():.2f}")

Loaded 109 records
Processing 1/109: Taman Kota Bagansiapiapi
  -> Updated from Wikipedia
Processing 2/109: Taman Makam Pahlawan
  -> Already has description
Processing 3/109: Tugu Keris
  -> Updated from Wikipedia
Processing 4/109: Pusat Latihan Gajah Riau
  -> Updated from Wikipedia
Processing 5/109: Tugu Bawang
  -> Updated from Wikipedia
Processing 6/109: Tugu Bambu Runcing
  -> Updated from Wikipedia
Processing 7/109: Tugu Perjuangan
  -> Updated from Wikipedia
Processing 8/109: Museum Daerah Sang Nila Utama
  -> Updated from Wikipedia
Processing 9/109: AKHBAR SOFTWARE HOUSE
  -> Generated simple description
Processing 10/109: KUA Air Dingin
  -> Updated from Wikipedia
Processing 11/109: Tugu Perbatasan Pekanbaru
  -> Updated from Wikipedia
Processing 12/109: Tugu Perbatasan
  -> Updated from Wikipedia
Processing 13/109: Tugu Perbatasan Siak - Bengkalis
  -> Generated simple description
Processing 14/109: Tugu Batas Bantan
  -> Generated simple description
Processing 15/109: Gerbang Pantai Selat Baru
  -> Generated simple description
Processing 16/109: Taman Kota
  -> Generated simple description
Processing 17/109: Batu Hitam
  -> Generated simple description
Processing 18/109: Halte Uin SUSKA
  -> Generated simple description
Processing 19/109: Ai'Home
  -> Generated simple description
Processing 20/109: Simpang Bambu Kuning
  -> Generated simple description
Processing 21/109: Air Panas Semurup
  -> Already has description
Processing 22/109: Jam Gento Bangko
  -> Generated simple description
Processing 23/109: Tugu Ikan
  -> Generated simple description
Processing 24/109: Kompleks Percandian Muaro Jambi
  -> Generated simple description
Processing 25/109: Tugu Bundaran Simpang Dado Pasar Buah Kota Jambi
  -> Generated simple description
Processing 26/109: Taman Pkk Thehok The Hok
  -> Generated simple description
Processing 27/109: Kantor Desa Lagan Tengah
  -> Generated simple description
Processing 28/109: taman budaya jambu
  -> Generated simple description
Processing 29/109: Candi Sialang
  -> Generated simple description
Processing 30/109: Menapo
  -> Generated simple description
Processing 31/109: Menapo
  -> Generated simple description
Processing 32/109: Menapo
  -> Generated simple description
Processing 33/109: Menapo
  -> Generated simple description
Processing 34/109: Margarana Memorial
  -> Generated simple description
Processing 35/109: Bali Butterfly Park
  -> Generated simple description
Processing 36/109: Museum Subak
  -> Already has description
Processing 37/109: Paintball
  -> Generated simple description
Processing 38/109: Pura Luhur Batukaru
  -> Already has description
Processing 39/109: Pura Susunan Wadonan
  -> Generated simple description
Processing 40/109: Museum Purbakala
  -> Generated simple description
Processing 41/109: Makam Jayaprana
  -> Generated simple description
Processing 42/109: Museum Situs Purbakala
  -> Generated simple description
Processing 43/109: Tenganan Pegringsingan
  -> Generated simple description
Processing 44/109: Shiva temple
  -> Generated simple description
Processing 45/109: Tegenungan Blangsinga
  -> Generated simple description
Processing 46/109: Brahma Arama Vihara
  -> Generated simple description
Processing 47/109: Pura Ulun Danu Batur
  -> Already has description
Processing 48/109: Pura Ibu Bendesa Basangalas
  -> Generated simple description
Processing 49/109: Pura Puseh Desa Adat Basangalas
  -> Generated simple description
Processing 50/109: Pura Batu Kolok (temple)
  -> Generated simple description
  -> Progress saved at 50 records
Processing 51/109: Pura Masceti (temple)
  -> Generated simple description
Processing 52/109: Mac Arthur Site
  -> Generated simple description
Processing 53/109: Tugu Salib
  -> Generated simple description
Processing 54/109: Kalibiru
  -> Already has description
Processing 55/109: Museum Lokabudaya Uncen
  -> Generated simple description
Processing 56/109: Situs Megalitik Tutari
  -> Generated simple description
Processing 57/109: Tugu Serui
  -> Generated simple description
Processing 58/109: Batupapan, rock layers beack
  -> Generated simple description
Processing 59/109: Danger Waves Sign!
  -> Generated simple description
Processing 60/109: Small Sea Village
  -> Generated simple description
Processing 61/109: Waves escape sign!
  -> Generated simple description
Processing 62/109: Pigeons Holes, actual pigeons
  -> Generated simple description
Processing 63/109: Crafts, mini row boats, Traditional Snake Drums
  -> Generated simple description
Processing 64/109: Old WWII plane hangars converted into houses
  -> Generated simple description
Processing 65/109: Wandos Mangled Forested Boat Beach
  -> Generated simple description
Processing 66/109: Coconuts beach
  -> Generated simple description
Processing 67/109: Beautiful Small Coconuts  Bay
  -> Generated simple description
Processing 68/109: Marluia peninsula
  -> Generated simple description
Processing 69/109: Traditional house
  -> Generated simple description
Processing 70/109: Rock mountain on the beach, giant coconut crabs here
  -> Generated simple description
Processing 71/109: Tugu Burung Enggang Pasar Panas Perbatasan Kalsel-Kalteng
  -> Generated simple description
Processing 72/109: Museum Lewu Hante
  -> Already has description
Processing 73/109: Tugu Selamat Datang Barito Timur
  -> Generated simple description
Processing 74/109: Feeding Cam Lakey
  -> Generated simple description
Processing 75/109: Tugu Proklamasi
  -> Already has description
Processing 76/109: Cagar Budaya Putri Mayang
  -> Generated simple description
Processing 77/109: Akasia
  -> Already has description
Processing 78/109: Bundaran PEMDA
  -> Generated simple description
Processing 79/109: Feeding Pondok Tangui
  -> Generated simple description
Processing 80/109: Tanjung Harapan
  -> Already has description
Processing 81/109: POHON SAWIT
  -> Generated simple description
Processing 82/109: Yayasan Orang Utan Internasional
  -> Generated simple description
Processing 83/109: Tugu Bundaran KB
  -> Generated simple description
Processing 84/109: Batas Waktu Feeding Station
  -> Generated simple description
Processing 85/109: Tam'mak Bugawan Dime
  -> Generated simple description
Processing 86/109: Tugu Rusa
  -> Generated simple description
Processing 87/109: Night walk
  -> Generated simple description
Processing 88/109: Tugu Adipura
  -> Already has description
Processing 89/109: Istana Isen Mulang
  -> Generated simple description
Processing 90/109: Zero Point
  -> Generated simple description
Processing 91/109: Toar Lummimuut
  -> Generated simple description
Processing 92/109: Walanda Maramis
  -> Already has description
Processing 93/109: Yesus Memberkati
  -> Generated simple description
Processing 94/109: Kantor Sinode GMIM
  -> Generated simple description
Processing 95/109: Auditorium Bukit Inspirasi
  -> Generated simple description
Processing 96/109: Hot springs
  -> Generated simple description
Processing 97/109: Japanese Cave
  -> Generated simple description
Processing 98/109: Japanese Cave
  -> Generated simple description
Processing 99/109: Waruga cemetry
  -> Generated simple description
Processing 100/109: Watu Pinabetengan
  -> Generated simple description
  -> Progress saved at 100 records
Processing 101/109: Benteng Moraya
  -> Generated simple description
Processing 102/109: Wooden House Factory
  -> Generated simple description
Processing 103/109: Gua Japeng
  -> Generated simple description
Processing 104/109: Monumen Tua Lokon Pinontoan Kayawu
  -> Generated simple description
Processing 105/109: Monumen Lilin
  -> Generated simple description
Processing 106/109: Tugu Adipura
  -> Already has description
Processing 107/109: Tugu Peringatan Worang
  -> Generated simple description
Processing 108/109: Tugu Jam
  -> Generated simple description
Processing 109/109: Tugu Ibukota Kabupaten
  -> Generated simple description

Completed!
Updated 96 descriptions
Results saved to /content/wisata_indonesia_enhanced.csv

Sample results:
                 Place_Name  City  \
0  Taman Kota Bagansiapiapi  Riau
1      Taman Makam Pahlawan  Riau
2                Tugu Keris  Riau
3  Pusat Latihan Gajah Riau  Riau
4               Tugu Bawang  Riau

                                         Description Rating
0  cerita masyarakat Bagansiapiapi secara turun t...    3.6
1  Taman Makam Pahlawan atau sering disingkat TMP...   None
2  Tugu Keris Siginjai adalah sebuah tugu atau mo...    3.9
3  memiliki Jembatan Khusus untuk Gajah karena sa...    4.7
4  Daftar kecamatan dan kelurahan di Kabupaten Tu...    4.0

Statistics:
Total records: 109
Records with description: 109
Records with rating: 96
Average rating: 4.26

In [62]:
enhanced_df.head()

,City,Place_Name,Category,Lat,Long,Description,Rating
0,Riau,Taman Kota Bagansiapiapi,park,2.162026,100.807612,cerita masyarakat Bagansiapiapi secara turun t...,3.6
1,Riau,Taman Makam Pahlawan,memorial,2.161243,100.803417,Taman Makam Pahlawan atau sering disingkat TMP...,None
2,Riau,Tugu Keris,monument,0.510272,101.452118,Tugu Keris Siginjai adalah sebuah tugu atau mo...,3.9
3,Riau,Pusat Latihan Gajah Riau,attraction,0.723431,101.411663,memiliki Jembatan Khusus untuk Gajah karena sa...,4.7
4,Riau,Tugu Bawang,monument,1.491430,102.089593,Daftar kecamatan dan kelurahan di Kabupaten Tu...,4.0

In [67]:
import pandas as pd
import numpy as np
from geopy.distance import geodesic
import re

class TourismDataMerger:
    def __init__(self):
        # Mapping kategori dari scraped data ke kategori target
        self.category_mapping = {
            'park': 'Taman Hiburan',
            'memorial': 'Budaya',
            'monument': 'Budaya',
            'attraction': 'Wisata Alam',
            'museum': 'Wisata Budaya',
            'boundary_stone': 'Budaya',
            'castle': 'Wisata Budaya',
            'wayside_cross': 'Tempat Ibadah',
            'archaeological_site': 'Wisata Budaya',
            'ruins': 'Wisata Budaya',
            'manor': 'Wisata Budaya',
            'yes': 'Wisata Alam'
        }

        self.target_categories = [
            'Wisata Alam', 'Wisata Petualangan', 'Taman Hiburan',
            'Cagar Alam', 'Budaya', 'Wisata Hiburan', 'Wisata Kuliner',
            'Pusat Perbelanjaan', 'Tempat Ibadah', 'Wisata Budaya', 'Bahari'
        ]

    def clean_place_name(self, name):
        """Membersihkan nama tempat untuk matching yang lebih baik"""
        if pd.isna(name):
            return ""
        cleaned = str(name).lower()
        cleaned = re.sub(r'[^\w\s]', ' ', cleaned)
        cleaned = re.sub(r'\s+', ' ', cleaned).strip()
        return cleaned

    def calculate_distance(self, lat1, lon1, lat2, lon2):
        """Menghitung jarak antara dua koordinat (KM)"""
        try:
            return geodesic((lat1, lon1), (lat2, lon2)).kilometers
        except:
            return float('inf')

    def find_matches(self, df1, df2, distance_threshold=5.0, name_similarity_threshold=0.7):
        """
        Mencari kecocokan antara dua dataset berdasarkan nama dan jarak.
        Returns list of dict: { idx1, idx2, score, distance, name_similarity }
        """
        matches = []
        for idx1, row1 in df1.iterrows():
            name1 = self.clean_place_name(row1['Place_Name'])
            lat1, lon1 = row1['Lat'], row1['Long']
            best_match, best_score = None, 0.0

            for idx2, row2 in df2.iterrows():
                name2 = self.clean_place_name(row2['Place_Name'])
                lat2, lon2 = row2['Lat'], row2['Long']

                # Jaccard similarity sederhana
                words1, words2 = set(name1.split()), set(name2.split())
                if not words1 or not words2:
                    name_similarity = 0.0
                else:
                    intersection = len(words1 & words2)
                    union = len(words1 | words2)
                    name_similarity = intersection / union if union else 0.0

                distance = self.calculate_distance(lat1, lon1, lat2, lon2)

                if distance <= distance_threshold and name_similarity >= name_similarity_threshold:
                    score = name_similarity * 0.7 + (1 - min(distance / distance_threshold, 1)) * 0.3
                    if score > best_score:
                        best_match = {
                            'idx1': idx1,
                            'idx2': idx2,
                            'score': score,
                            'distance': distance,
                            'name_similarity': name_similarity
                        }
                        best_score = score

            if best_match:
                matches.append(best_match)

        return matches

    def map_category(self, original_category):
        """Mapping kategori scraped → kategori target."""
        if pd.isna(original_category):
            return 'Wisata Alam'
        return self.category_mapping.get(str(original_category).lower(), 'Wisata Alam')

    def merge_datasets(self, primary_df, secondary_df,
                       distance_threshold=5.0, name_similarity_threshold=0.5):
        """
        Menggabungkan dua DataFrame:
        - primary_df (DataFrame in‐memory)
        - secondary_df (DataFrame in‐memory)
        Prioritaskan primary_df: hanya update kolom kosong,
        tambahkan record baru jika belum ada.
        """
        print("Starting dataset merge...")
        print(f"Primary dataset: {len(primary_df)} records")
        print(f"Secondary dataset: {len(secondary_df)} records")

        # 1) Copy primary_df → merged_df
        merged_df = primary_df.copy()

        # 2) Pastikan kolom dasar ada di merged_df
        required_columns = ['Place_Id', 'Place_Name', 'Description', 'Category', 'City',
                            'Price', 'Rating', 'Time_Minutes', 'Lat', 'Long']
        for col in required_columns:
            if col not in merged_df.columns:
                if col == 'Place_Id':
                    merged_df[col] = range(1, len(merged_df) + 1)
                elif col == 'Price':
                    merged_df[col] = 0
                elif col == 'Time_Minutes':
                    merged_df[col] = 60
                else:
                    merged_df[col] = np.nan

        # 3) Cari pasangan match antara primary_df dan secondary_df
        matches = self.find_matches(
            merged_df, secondary_df,
            distance_threshold, name_similarity_threshold
        )
        print(f"Found {len(matches)} potential matches")

        used_secondary_indices = set()
        updated_count = 0

        # 4) Update kolom kosong di merged_df berdasarkan hasil matching
        for match in matches:
            idx1, idx2 = match['idx1'], match['idx2']
            if idx2 in used_secondary_indices:
                continue

            # Ambil baris dari merged_df & secondary_df
            primary_row = merged_df.loc[idx1]
            secondary_row = secondary_df.loc[idx2]
            updates_made = []

            # a) Update Description jika kosong atau terlalu pendek
            if (pd.isna(primary_row['Description']) or
                len(str(primary_row['Description'])) < 20):
                desc2 = secondary_row.get('Description', "")
                if pd.notna(desc2) and len(str(desc2)) >= 20:
                    merged_df.at[idx1, 'Description'] = desc2
                    updates_made.append('Description')

            # b) Update Rating jika kosong atau 0
            raw_rating = secondary_row.get('Rating')
            if isinstance(raw_rating, str):
                raw_rating = raw_rating.strip().lower()
                if raw_rating in ['none', 'nan', '']:
                    raw_rating = np.nan
                else:
                    try:
                        raw_rating = float(raw_rating)
                    except:
                        raw_rating = np.nan
            raw_rating = pd.to_numeric(raw_rating, errors='coerce')

            if (pd.isna(primary_row['Rating']) or primary_row['Rating'] == 0) and pd.notna(raw_rating):
                merged_df.at[idx1, 'Rating'] = raw_rating
                updates_made.append('Rating')

            # c) Update Category jika kosong
            if pd.isna(primary_row['Category']):
                merged_df.at[idx1, 'Category'] = self.map_category(secondary_row.get('Category'))
                updates_made.append('Category')

            if updates_made:
                updated_count += 1
                print(f"Updated row {idx1}: {', '.join(updates_made)} - {primary_row['Place_Name']}")

            used_secondary_indices.add(idx2)

        # 5) Tambahkan record baru (yang tidak match) dari secondary_df
        print("Adding new records from secondary dataset...")
        next_id = merged_df['Place_Id'].max() + 1 if not merged_df['Place_Id'].isna().all() else 1
        new_records = []

        for idx, row in secondary_df.iterrows():
            if idx in used_secondary_indices:
                continue

            raw_rating = row.get('Rating')
            if isinstance(raw_rating, str):
                raw_rating = raw_rating.strip().lower()
                if raw_rating in ['none', 'nan', '']:
                    raw_rating = np.nan
                else:
                    try:
                        raw_rating = float(raw_rating)
                    except:
                        raw_rating = np.nan
            raw_rating = pd.to_numeric(raw_rating, errors='coerce')

            new_records.append({
                'Place_Id': next_id,
                'Place_Name': row.get('Place_Name', ""),
                'Description': row.get('Description', ""),
                'Category': self.map_category(row.get('Category')),
                'City': row.get('City', ""),
                'Price': 0,
                'Rating': raw_rating,
                'Time_Minutes': 60,
                'Lat': row.get('Lat', np.nan),
                'Long': row.get('Long', np.nan)
            })
            next_id += 1

        if new_records:
            new_df = pd.DataFrame(new_records)
            merged_df = pd.concat([merged_df, new_df], ignore_index=True)
            print(f"Added {len(new_records)} new records")

        # 6) Bersihkan & standardisasi data
        merged_df = self.clean_merged_data(merged_df)

        print(f"\nMerge completed!")
        print(f"Final dataset: {len(merged_df)} records")
        print(f"Updated existing records: {updated_count}")
        added_count = len(merged_df) - len(primary_df)
        print(f"Actual new records added: {added_count}\n")

        return merged_df

    def clean_merged_data(self, df):
        """Membersihkan & standardisasi semua baris setelah merge"""
        # a) Standar kategori
        df['Category'] = df['Category'].fillna('Wisata Alam')
        df['Category'] = df['Category'].apply(
            lambda x: x if x in self.target_categories else 'Wisata Alam'
        )

        # b) Bersihkan Rating
        df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce').clip(0, 5).fillna(0)

        # c) Bersihkan Price
        df['Price'] = pd.to_numeric(df['Price'], errors='coerce').fillna(0).clip(0)

        # d) Bersihkan Time_Minutes
        df['Time_Minutes'] = pd.to_numeric(df['Time_Minutes'], errors='coerce').fillna(60).clip(15, 480)

        # e) Bersihkan Lat/Long
        df['Lat'] = pd.to_numeric(df['Lat'], errors='coerce')
        df['Long'] = pd.to_numeric(df['Long'], errors='coerce')

        before = len(df)
        df = df.dropna(subset=['Lat', 'Long']).reset_index(drop=True)
        if before != len(df):
            print(f"Removed {before - len(df)} records with invalid coordinates")

        return df

def merge_tourism_datasets(primary_df, secondary_df,
                           output_path=None,
                           distance_threshold=10.0,
                           name_similarity_threshold=0.3):
    """
    Menggabungkan dua DataFrame in-memory:
    - primary_df: DataFrame (combined_tourism_df_cleaned.copy())
    - secondary_df: DataFrame (pd.read_csv("wisata_indonesia_enhanced.csv"))
    Jika output_path diberikan (string), maka hasil juga disimpan ke CSV.
    """
    merger = TourismDataMerger()
    merged_df = merger.merge_datasets(
        primary_df.copy(),
        secondary_df.copy(),
        distance_threshold,
        name_similarity_threshold
    )

    if output_path:
        merged_df.to_csv(output_path, index=False)
        print(f"Merged dataset saved to {output_path}")

    print("\n=== SAMPLE MERGED DATA (first 10 rows) ===")
    print(merged_df[['Place_Name', 'Category', 'City', 'Description', 'Rating', 'Lat', 'Long']].head(10))

    return merged_df

# =======================
# Contoh Pemanggilan Kode
# =======================
if __name__ == "__main__":
    pass

In [68]:
primary_data = combined_tourism_df_cleaned.copy()
secondary_data = pd.read_csv("/content/wisata_indonesia_enhanced.csv")

final_df = merge_tourism_datasets(
    primary_data,
    secondary_data,
    output_path="/content/final_merged_tourism_data.csv"
)

Starting dataset merge...
Primary dataset: 604 records
Secondary dataset: 109 records
Found 5 potential matches
Updated row 558: Rating - Auditorium Bukit Inspirasi
Updated row 606: Rating - Museum Lokabudaya Uncen
Updated row 454: Rating - Pusat Latihan Gajah Riau
Adding new records from secondary dataset...
Added 104 new records

Merge completed!
Final dataset: 708 records
Updated existing records: 3
Actual new records added: 104

Merged dataset saved to /content/final_merged_tourism_data.csv

=== SAMPLE MERGED DATA (first 10 rows) ===
                                Place_Name            Category          City  \
0                       3 WWII rusty tanks         Wisata Alam         Papua
1          AMA Associated Mission Aviation         Wisata Alam  Papua Tengah
2  Agropuro Multifarm & Outbound Adventure  Wisata Petualangan          Riau
3                        Air Mancur Menari       Taman Hiburan      Surabaya
4                        Air Panas Geragai         Wisata Alam         Jambi
5                   Air Terjun Kali Pancur          Cagar Alam      Semarang
6                  Air Terjun Kedung Pedut          Cagar Alam    Yogyakarta
7                      Air Terjun Pelabian         Wisata Alam         Jambi
8                      Air Terjun Semirang          Cagar Alam      Semarang
9                    Air Terjun Sri Gethuk          Cagar Alam    Yogyakarta

                                         Description  Rating       Lat  \
0                     Tempat wisata menarik di Papua     0.0 -2.571545
1              Tempat wisata menarik di Papua Tengah     0.0 -3.366112
2                      Tempat wisata menarik di Riau     0.0  0.582866
3  Jembatan Kenjeran dengan air mancur menarinya ...     4.4 -7.235693
4                      #SURVEYGLAM ##GLAMBANDUNG2023     0.0 -1.147297
5  Kali Pancur Getasan merupakan kawasan wisata a...     4.1 -7.358096
6  Air Terjun Kedung Pedut atau biasa disebut Cur...     4.5 -7.769988
7                     Tempat wisata menarik di Jambi     0.0 -1.121900
8  Terletak di lereng Gunung Ungaran bagian utara...     4.4 -7.166297
9  Air Terjun Sri Gethuk merupakan salah satu obj...     4.4 -7.943178

         Long
0  140.709192
1  135.494587
2  101.418606
3  112.795523
4  103.677157
5  110.421068
6  110.121071
7  102.959056
8  110.381068
9  110.489240

In [70]:
final_df.head()

,Place_Id,Place_Name,Description,Category,City,Price,Rating,Time_Minutes,Lat,Long,key
0,611,3 WWII rusty tanks,Tempat wisata menarik di Papua,Wisata Alam,Papua,0,0.0,60.0,-2.571545,140.709192,papua|3 wwii rusty tanks
1,603,AMA Associated Mission Aviation,Tempat wisata menarik di Papua Tengah,Wisata Alam,Papua Tengah,0,0.0,60.0,-3.366112,135.494587,papua tengah|ama associated mission aviation
2,454,Agropuro Multifarm & Outbound Adventure,Tempat wisata menarik di Riau,Wisata Petualangan,Riau,0,0.0,60.0,0.582866,101.418606,riau|agropuro multifarm & outbound adventure
3,394,Air Mancur Menari,Jembatan Kenjeran dengan air mancur menarinya ...,Taman Hiburan,Surabaya,35000,4.4,45.0,-7.235693,112.795523,surabaya|air mancur menari
4,463,Air Panas Geragai,#SURVEYGLAM ##GLAMBANDUNG2023,Wisata Alam,Jambi,0,0.0,60.0,-1.147297,103.677157,jambi|air panas geragai

In [72]:
import pandas as pd
import numpy as np

# Misal final_df sudah ada di memori
# Cek dulu berapa banyak Rating=0
print("Sebelum imputasi, jumlah Rating=0:", (final_df['Rating'] == 0).sum())

def impute_rating_by_city_category(df):
    df = df.copy()

    # 1. Tandai Rating=0 sebagai NaN agar bisa diimputasi
    df['Rating'] = df['Rating'].replace(0, np.nan)

    # 2. Hitung rata-rata per grup (City, Category) dan isi NaN dengan rata-rata itu
    df['Rating'] = df.groupby(['City', 'Category'])['Rating'] \
                     .transform(lambda grp: grp.fillna(grp.mean()))

    # 3. Jika setelah langkah (2) masih ada NaN (artinya grup (City,Category) semuanya NaN),
    #    isi dengan rata-rata per Category
    df['Rating'] = df.groupby('Category')['Rating'] \
                     .transform(lambda grp: grp.fillna(grp.mean()))

    # 4. Jika masih ada NaN (misalnya Category baru yang semua NaN), isi dengan rata-rata keseluruhan
    global_mean = df['Rating'].mean()
    df['Rating'] = df['Rating'].fillna(global_mean)

    # 5. Pastikan tetap dalam rentang 0–5
    df['Rating'] = df['Rating'].clip(0, 5)

    return df

# Terapkan fungsi imputasi
final_df = impute_rating_by_city_category(final_df)

# Tampilkan hasil
print("Setelah imputasi, jumlah Rating=0:", (final_df['Rating'] == 0).sum())
print("\nContoh beberapa baris pertama:")
print(final_df[['Place_Name', 'City', 'Category', 'Rating']].head(10))

Sebelum imputasi, jumlah Rating=0: 175
Setelah imputasi, jumlah Rating=0: 0

Contoh beberapa baris pertama:
                                Place_Name          City            Category  \
0                       3 WWII rusty tanks         Papua         Wisata Alam
1          AMA Associated Mission Aviation  Papua Tengah         Wisata Alam
2  Agropuro Multifarm & Outbound Adventure          Riau  Wisata Petualangan
3                        Air Mancur Menari      Surabaya       Taman Hiburan
4                        Air Panas Geragai         Jambi         Wisata Alam
5                   Air Terjun Kali Pancur      Semarang          Cagar Alam
6                  Air Terjun Kedung Pedut    Yogyakarta          Cagar Alam
7                      Air Terjun Pelabian         Jambi         Wisata Alam
8                      Air Terjun Semirang      Semarang          Cagar Alam
9                    Air Terjun Sri Gethuk    Yogyakarta          Cagar Alam

     Rating
0  4.376923
1  4.311387
2  4.384017
3  4.400000
4  4.400000
5  4.100000
6  4.500000
7  4.400000
8  4.400000
9  4.400000

In [73]:

final_df['Rating'] = final_df['Rating'].round(1)

# Tampilkan hasil setelah pembulatan
print("\nContoh beberapa baris pertama setelah pembulatan:")
print(final_df[['Place_Name', 'City', 'Category', 'Rating']].head(10))

Contoh beberapa baris pertama setelah pembulatan:
                                Place_Name          City            Category  \
0                       3 WWII rusty tanks         Papua         Wisata Alam
1          AMA Associated Mission Aviation  Papua Tengah         Wisata Alam
2  Agropuro Multifarm & Outbound Adventure          Riau  Wisata Petualangan
3                        Air Mancur Menari      Surabaya       Taman Hiburan
4                        Air Panas Geragai         Jambi         Wisata Alam
5                   Air Terjun Kali Pancur      Semarang          Cagar Alam
6                  Air Terjun Kedung Pedut    Yogyakarta          Cagar Alam
7                      Air Terjun Pelabian         Jambi         Wisata Alam
8                      Air Terjun Semirang      Semarang          Cagar Alam
9                    Air Terjun Sri Gethuk    Yogyakarta          Cagar Alam

   Rating
0     4.4
1     4.3
2     4.4
3     4.4
4     4.4
5     4.1
6     4.5
7     4.4
8     4.4
9     4.4

In [75]:
final_df.head()

,Place_Id,Place_Name,Description,Category,City,Price,Rating,Time_Minutes,Lat,Long,key
0,611,3 WWII rusty tanks,Tempat wisata menarik di Papua,Wisata Alam,Papua,0,4.4,60.0,-2.571545,140.709192,papua|3 wwii rusty tanks
1,603,AMA Associated Mission Aviation,Tempat wisata menarik di Papua Tengah,Wisata Alam,Papua Tengah,0,4.3,60.0,-3.366112,135.494587,papua tengah|ama associated mission aviation
2,454,Agropuro Multifarm & Outbound Adventure,Tempat wisata menarik di Riau,Wisata Petualangan,Riau,0,4.4,60.0,0.582866,101.418606,riau|agropuro multifarm & outbound adventure
3,394,Air Mancur Menari,Jembatan Kenjeran dengan air mancur menarinya ...,Taman Hiburan,Surabaya,35000,4.4,45.0,-7.235693,112.795523,surabaya|air mancur menari
4,463,Air Panas Geragai,#SURVEYGLAM ##GLAMBANDUNG2023,Wisata Alam,Jambi,0,4.4,60.0,-1.147297,103.677157,jambi|air panas geragai

In [76]:
final_df.to_csv('/content/dataset_tempat_final.csv', index=False)
print("Final cleaned data saved to dataset_tempat_final.csv")

Final cleaned data saved to dataset_tempat_final.csv